### ISSUE TITLE
Connecting rpi3 b+ through UART cable

### ISSUE THREAD

**Issue by Hacklog24** [OP-TEE/optee_os#2770] opened 2019-01-29 14:45 UTC
@jbech-linaro @igoropaniuk
Good evening,
I connected the uart cable between pc and raspberry, the serial port is seen by the system, but neither through minicom nor via putty on windows, I can run a test. Once I start minicom, I get only the command list, but I can not give an input. Can someone help me please?

PS: I followed the wiring instructions and software settings.

Thanks again.

**Comment by jbech-linaro** [comment] 2019-01-29 14:48
Hi,

I typically do:
```bash
$ picocom -b 115200 /dev/ttyUSB0
```
Then I get all boot logs, U-Boot command prompt, kernel boot log, busybox prompt.  You don't see anything like that?

**Comment by Hacklog24** [comment] 2019-01-29 15:19
I executed the command and I receive this...

![test](https://user-images.githubusercontent.com/42044367/51918306-940cee80-23e1-11e9-8f56-46d5b12f39b0.png)

**Comment by jbech-linaro** [comment] 2019-01-29 15:40
So far it looks similar to what I see, next when you power up the device, you see? Still nothing? Have you cross and triple checked that you've put the PIN correctly on the UART?

**Comment by igoropaniuk** [comment] 2019-01-29 20:36
Can you connect HDMI cable and check if there is any output? just to exclude the possible wrong pin-out

**Comment by Hacklog24** [comment] 2019-01-29 22:45
Also in this case no result. I noticed that the LED remains red even with another card (with another operating system). At this point I doubt the operation of the raspberry...
Could this be the problem?

**Comment by jbech-linaro** [comment] 2019-01-30 10:31
@Hacklog24 , can you try your device using a plain Raspbian without involving OP-TEE at all. I.e., a plain setup based on the information as provided by https://raspberrypi.org? If you have no success there, then I'm afraid your device is broken.

**Comment by Hacklog24** [comment] 2019-01-31 07:31
Good morning @jbech-linaro,

I'm sorry for the late reply but I did some tests. I tried another device with NOOBS and it also works with the UART cable. Then I tried with the SD card containing OP-TEE but the red LED flashes and nothing happens.

I followed the whole procedure up to the "make img-help" command, formatted and loaded the SD card as shown, but when it is turned on, it seems that the system is not read. I have prepared the SD card only with OP-TEE files, I don't think I need a pre-installed distro, right? Thank you very much for your help and sorry for the trivial question.

**Comment by jbech-linaro** [comment] 2019-01-31 07:46
> I tried another device with NOOBS and it also works with the UART cable.

OK, then we know that the device is working at least, that's a good start.

> I don't think I need a pre-installed distro, right?

Right, you **shall** not use **any** pre-installed distro. It was just to rule out whether the device was working or not.

Related, I have a task of gather **all** OP-TEE documentation in a single place and at the same re-write it to *.rst. As we're speaking I'm at the RPi3 document. Part of that work is also up ensure that the instructions are up-to-date, which means that I'm trying thing out on real device(s) also. So stay tuned for an update. Having that said, we released OP-TEE 3.4.0 last Friday and RPi3 was tested succesfully for that release.

**Comment by jbech-linaro** [comment] 2019-01-31 08:17
@Hacklog24 and I can confirm that the instructions are up-to-date. My test starting from scratch turned out to work as expected (this is the "default" with SD-card. Haven't tested using NFS yet).

**Comment by Hacklog24** [comment] 2019-01-31 12:04
@jbech-linaro 
Thank you so much for all the information !!
It's a huge and fantastic job and you're always available.
Has it also been tested for raspberry pi 3b +? If this is not a possible cause, should I recompile the rpi3 manifest with a specific version?

Thank you so much for all the help.

**Comment by jbech-linaro** [comment] 2019-01-31 14:17
> Has it also been tested for raspberry pi 3b +?

I'm copy / pasting my reply from #2783 that probably will answer your questions and give guidance.

---
Hi,

Feels like I'm repeating in each and every ticket about RPi3 but anyways ...

1. We're updating the documentation. A snapshot of the work in progress can be found here for RPi3: https://optee.readthedocs.io/building/devices/rpi3.html. Even though not fully ready, please use those for general RPi3 information as well as for standard setup with SD-card  (NFS, JTAG has not been verified yet on the new updated instructions). There are many clarifications on that page about what is supposed to work and what's not, what version of RPi hardware and what not etc. ETA for updated instructions are ~April 2019.

2. Today 2019-01-31 I've created a video clip while I was verifying the instructions. I.e., a full setup from scratch, you will find that here (I'm going add narrative audio later on to describe more what's going on): 
[![OP TEE on Raspberry Pi 3 with SD card](https://img.youtube.com/vi/-IcC2b3AJdA/0.jpg)](https://youtu.be/-IcC2b3AJdA)

Since I did "2" today and it is from scratch, it should be fairly easy to follow along if you use the upcoming documentation + look at (and pause) the video.

// Joakim 
---

**Comment by Hacklog24** [comment] 2019-01-31 23:33
@jbech-linaro 
Good evening,
I have no words to thank you for all the work done. Thank you for answering all my questions and especially for the video. It's fantastic.

I will try to redo all the steps from the beginning, using the updated documentation and the tutorial, hoping it will work. In case of a negative result, I will try with a previous version of the raspberry pi.

Thanks a lot for the help.

**Comment by Hacklog24** [comment] 2019-02-02 13:44
@jbech-linaro 
Hello again,

I redid the whole procedure, also changing the SD card but with a negative result. Once the raspberry is powered up, the red LED flashes and nothing happens on the terminal. Do you suggest me to change raspberry and try the normal 3b?

Thank you so much.

**Comment by Hacklog24** [comment] 2019-02-03 21:15
@jbech-linaro 
UPDATE

I managed to boot the system on the raspi b+ but it seems that the kernel did not load the tee-supplicant. When I launch the "xtest" command, I receive:

Run the test suite with level = 0
TEE test application started with device [(null)]
Failed to open the TEE context: 0xffff0008

while if I launch "tee-supplicant &" I get:

ERR [113] TSUP: main: 678: can not find an OP-TEE supplicant device

and no output if I launch "dmesg | grep optee"

How can I solve? Thank you so much and sorry for the many questions...

**Comment by jforissier** [comment] 2019-02-04 00:04
Do you have `CONFIG_TEE` and `CONFIG_OPTEE` in `linux/.config`?

**Comment by Hacklog24** [comment] 2019-02-05 16:17
Hi,

waiting for the guide, is there any advice you could give me to solve? It seems that the kernel did not load the tee-supplicant. When I start the system, I see "tee-supplicant or TEE device not found".

I'd like to try the environment as soon as possible. I have already written my experience with B+, problems, solutions and more, as soon as it works I can also post it, maybe it could help someone.

Thank you all.

**Comment by Hacklog24** [comment] 2019-02-05 16:52
Thanks for the advice

I have already configured OP-TEE on QEMU to understand how it works. I would like to take advantage of having it on an embedded system and to learn.

**Comment by Hacklog24** [comment] 2019-02-05 23:44
@jbech-linaro 
Hello,

thank you very much for all the help you gave me. I solved my problem on the raspberry pi 3 b+, now it works with both UART and HDMI cables. Feel free to contact me for any clarification and I suggest to follow the guide posted by @dkarnikis who solved the problem.

Guide --> https://github.com/dkarnikis/rpi3bplus-optee

Thank you all

**Comment by jbech-linaro** [comment] 2019-02-06 06:14
Thanks! I'm closing the ticket since there is a solution for the problem now.

**Closed by jbech-linaro** 2019-02-06 06:14 UTC
