### ISSUE TITLE
kernel sleep during handle rpc call

### ISSUE THREAD

**Issue by zhizhouzh** [OP-TEE/optee_os#869] opened 2016-06-22 08:32 UTC
Hi experts,

When run xtest 1013, I often get this assertion:

> ERROR:   TEE-CORE: Assertion 'l->curr_thread == -1' failed at core/arch/arm/kernel/thread.c:502

So I dive into this case. It seems because of `optee_do_call_with_arg` in kernel switch its cpu during handle rpc call. Here is the flow:

- `optee_os` calls `thread_rpc`
- kernel handle this rpc with `optee_do_call_with_arg`, but `optee_handle_rpc` in `optee_do_call_with_arg` may sleep, and this process may wakeup on another cpu
- kernel switch to another cpu, and call smc to enter `optee_os` again
- `optee_os` check `l->curr_thread` in `thread_resume_from_rpc`, and this may equals to -1.

and I add below code in linux kernel, this case doesn't happen again:

```
diff --git a/drivers/tee/optee/call.c b/drivers/tee/optee/call.c
index c567f98..97d896b 100644
--- a/drivers/tee/optee/call.c
+++ b/drivers/tee/optee/call.c
@@ -110,6 +110,11 @@ u32 optee_do_call_with_arg(struct tee_context *ctx, phys_addr_t parg)
        struct optee_call_waiter w;
        struct optee_rpc_param param = { };
        u32 ret;
+       struct cpumask mask;
+
+       cpumask_clear(&mask);
+       cpumask_set_cpu(current->on_cpu, &mask);
+       sched_setaffinity(current->pid, &mask);
 
        param.a0 = OPTEE_SMC_CALL_WITH_ARG;
        reg_pair_from_64(&param.a1, &param.a2, parg);
```

If I didn't do something wrong, this would be a bug. How would you handle this?

Thank you!

**Comment by jenswi-linaro** [comment] 2016-06-22 08:37
Hi,

There's a fix related to this committed to the master branch, please test with the latest from master branch to see if the problem is still there.

Thanks,
Jens

**Comment by zhizhouzh** [comment] 2016-06-22 09:36
Hi Jens,

I merge the latest code. But this bug still occurs. Can you point out which patch is aimed to this bug?

Thanks!

**Comment by jenswi-linaro** [comment] 2016-06-22 10:13
I thinking of b50c6a0fa1cc2deb0010cfdcae58fdaffe0ed951 (core: arm32: fix masking exceptions on exit)

**Comment by zhizhouzh** [comment] 2016-06-22 10:32
I think they are not the same bug. (And I am using arm64 soc)

This bug is caused by `assert(l->curr_thread == -1);` .

In `thread_resume_from_rpc`,  curr_thread is read from percpu variable, and because kernel do task migration, when get back to optee os, the previous thread read this variable from another cpu. It must not get the right value. 

```
struct thread_core_local *l = thread_get_core_local();
 assert(l->curr_thread == -1);
```

**Comment by jenswi-linaro** [comment] 2016-06-22 10:39
OK. Task migration is supposed to be supported by secure world so we need to fix it there. To me it looks like there's some exit path that doesn't set `l->curr_thread` to `-1`.

**Comment by zhizhouzh** [comment] 2016-06-22 11:38
Actually the first cpu set this variable. But the resume path is executed on another cpu. So it can possibly be any value, depends on the context of second cpu.

**Comment by jenswi-linaro** [comment] 2016-06-22 11:49
When a cpu isn't in secure mode 'l->curr_thread` should always be `-1`, and obviously a cpu can't enter secure mode if it's already in secure mode.

**Comment by zhizhouzh** [comment] 2016-06-23 01:11
You're right. I didn't take that into consideration. So there should be another bug. I will dig into it.

**Comment by jenswi-linaro** [comment] 2016-06-23 08:53
Thanks.

**Comment by zhizhouzh** [comment] 2016-06-27 11:11
I have spent another several days to check it. But it seems all exit path have set this value. It looks strange..

**Comment by jenswi-linaro** [comment] 2016-06-27 11:15
Are you using one of our supported platforms or a custom port?

**Comment by zhizhouzh** [comment] 2016-06-27 11:32
It's vexpress board. And tested in arm fastmodel.
I just execute tee-supplicant and xtest 1013. It's about to occur every 3 tries.
Can you reproduce it?

**Comment by jenswi-linaro** [comment] 2016-06-27 11:35
So you're using an unmodified setup, Including ARM-TF? I haven't seen this error before, I give it a try later.

**Comment by zhizhouzh** [comment] 2016-06-27 11:46
Thank you. There are some changes. And we can pass other xtest.

**Comment by jenswi-linaro** [comment] 2016-06-27 11:58
Did you change anything with how interrupts are handled? Because if there's a such exception to EL3, OP-TEE doesn't have a chance to update `l->curr_thread`.

**Comment by zhizhouzh** [comment] 2016-06-27 12:21
I didn't configure/enable any fiq in opteeos. And for irq from kernel side, I think it's ok.

**Comment by jenswi-linaro** [comment] 2016-06-28 06:45
Since you're able to reproduce it on FVP, why not test with an unmodified setup to see if you still have the problem.

We're running those tests all the time on different platforms and don't have that problem.

**Comment by zhizhouzh** [comment] 2016-06-29 01:07
We also made some tiny changes to FVP. So you don't have this problem? I will check our changes to opteeOS. Thank you!

**Comment by jbech-linaro** [comment] 2016-06-29 08:37
@zhizhouzh I've updated to latest version of OP-TEE according to the image below (2.1.0 that was released yesterad). Everything works fine and I've also tried running 1013 in a loop (ten times). No issues found (log is [here](https://transfer.sh/R0P59/1013.log)). Based on that and the comment it seems like it is your local changes that triggers the behavior. I will close this ticket for now. If you are able to trigger the issue on a **non-modified** setup, then please re-open the issue again.
![screenshot from 2016-06-29 09-45-07](https://cloud.githubusercontent.com/assets/6168937/16445895/339e4e5c-3de5-11e6-9e11-278db3103302.png)

**Closed** 2016-06-29 08:37 UTC
