### ISSUE TITLE
BUG: assert and zombie

### ISSUE THREAD

**Issue by wanchaoshan** [OP-TEE/optee_os#925] opened 2016-07-18 03:54 UTC
# when we run the script on the version 2.0 about 2 hours, the assert will happen 
script:                                                        
for i in `seq 1 # 100000`;
do
./xtest 1013
done

assert:
    /*  
     * If ctx->mmu == NULL we must not have user mapping active,
     * if ctx->mmu != NULL we must have user mapping active.
     */
    assert(((ctx && (ctx->flags & TA_FLAG_USER_MODE) ?
            to_user_ta_ctx(ctx)->mmu : NULL) == NULL) ==
        !core_mmu_user_mapping_is_active());

# Now, we update to stable vision 2.10, execute the same script, the  system will go to the dead state. Following is the last log messge.
Message:
[23:55:52]DEBUG:   [0x0] TEE-CORE:init_session_with_signed_ta:616:       dyn TA : e13010e0-2ae1-11e5-896a0002a5d5c51b
[23:55:52]DEBUG:   [0x0] TEE-CORE:wq_rpc:57: wake  thread 1 0x700646e0
[23:55:53]DEBUDEG:B U G :[ 0 x [0]0 x1TE]E -TCEEOR-ECO:wRqE:_rwpqc_:r5pc7:: 57sl:e wepa kteh  retahdr ea0 d0 0x7 00x06760057686
[23:55:53]78                                                                                                                   5
[23:55:53]DEDBEUBUG:G :    [ 0[x0x0]1 ]T ETEE-EC-COROERE:w:qw_q_rprcpc:5:75:7 :s lweakepe  t htrheraead d0  00 x07x07006066567587

**Comment by jenswi-linaro** [comment] 2016-07-18 10:19
Which platform are you testing on?

**Comment by jbech-linaro** [comment] 2016-07-19 07:22
@wanchaoshan I've been running `xtest 1013` for 21 hours now without any interruption (on RPi3) and I haven't seen the problem so far, so it seems like I cannot reproduce the issue. Like Jens asked, what platform are you using?

**Comment by wanchaoshan** [comment] 2016-07-19 08:08
@jbech-linaro @jenswi-linaro  I describe the problem about assertion again:
We add codes before assertion like this:
 #define CHECK_COND()  !(((ctx && (ctx->flags & TA_FLAG_USER_MODE) ? \
             to_user_ta_ctx(ctx)->mmu : NULL) == NULL) == !core_mmu_user_mapping_is_active())

{
    int xby_first_check = CHECK_COND();

    if (xby_first_check)
    {   
        int xby_second_check = CHECK_COND();
        int xby_third_check;
        xby_third_check = CHECK_COND();    
            
        temp_flag = ctx->flags; 
        mmu_temp = to_user_ta_ctx(ctx)->mmu;
        mapping_temp = !core_mmu_user_mapping_is_active();
        core_id = get_core_pos();
            
        {   
            DMSG("########ctx->flag = 0X%x, core_id = 0x%x\n", temp_flag, (unsigned int)core_id);
        }   
        if (mmu_temp != NULL)
        {   
            DMSG("########MMU is OK\n");
        }   
        else
            DMSG("########MMU is NULL\n");
                
        DMSG("###########core id = 0x%x\n", (unsigned int)get_core_pos());  
        DMSG("after = ############ 0x%x\n", mapping_temp);
        DMSG("xby_debug in tee_ta_set_current_session, value is %d, %d, %d\n", xby_first_check, xby_second_check, xby_third_check);

    }  

We got a strange result that the code entered into if indeed, but according to the log messages, it did not meet the conditions.
Lately, we updated the code version to 2.10 and verify the problem again.we found  there are some difference that the assertion  no longer happened, the system is stopped, just like I said it is in dead state, log message is like this:

[23:55:52]DEBUG: [0x0] TEE-CORE:init_session_with_signed_ta:616: dyn TA : e13010e0-2ae1-11e5-896a0002a5d5c51b
[23:55:52]DEBUG: [0x0] TEE-CORE:wq_rpc:57: wake thread 1 0x700646e0
[23:55:53]DEBUDEG:B U G :[ 0 x [0]0 x1TE]E -TCEEOR-ECO:wRqE:rwpqc:r5pc7:: 57sl:e wepa kteh retahdr ea0 d0 0x7 00x06760057686
[23:55:53]78 5
[23:55:53]DEDBEUBUG:G : [ 0[x0x0]1 ]T ETEE-EC-COROERE:w:qw_q_rprcpc:5:75:7 :s lweakepe t htrheraead d0 00 x07x07006066567587

Last night, I burned the version 2.0, shut down one cpu core, the assertion has not happened yet.
 And, the platform is our own IC, it is still in the validation phase.

**Comment by jenswi-linaro** [comment] 2016-07-19 08:23
There's contention on `tee_ta_mutex`. When the mutex is unlocked and another thread is waiting for the mutex the thread doing the unlock need to RPC to wake up the thread sleeping in normal world. This could be where the thread doing the wakeup for some reason hangs before the wakeup is completed.

Since we survived 21 hours on a RPi3 I guess the problem is in the port to your platform.  Interrupt routing from secure world to normal world is where I would have started looking for the problem.

**Comment by jbech-linaro** [comment] 2016-07-19 14:31
Just an update, I've left it running on the desk and it has been running for about 28 hours now only running 1013 (and I've checked that it runs on all 4 cores). So far no issues seen. I'll shut it down now.

**Comment by JammyZhou** [comment] 2016-07-23 12:34
@wanchaoshan is GICv3 mode or GICv2 compatible mode used on your platform? I think GICv2 compatible mode is used by default on other ARM platforms now.

**Comment by wanchaoshan** [comment] 2016-07-25 00:48
It is only GICv3 mode.

**Comment by jforissier** [comment] 2016-08-04 13:06
FWIW, I did see this same assertion a couple of time as I was porting OP-TEE to D02.

> ERROR:   TEE-CORE: Assertion '((ctx && (ctx->flags & TA_FLAG_USER_MODE) ? to_user_ta_ctx(ctx)->mmu : NULL) == NULL) == !core_mmu_user_mapping_is_active()' failed at core/kernel/tee_ta_manager.c:637

The first time it occurred, I was running 12 instances of `aes-perf` simultaneously (the board has 16 cores and CFG_NUM_THREADS was set to 16 or 8, I don't remember). Then I saw it again during another concurrency test. At that time, my D02 code was based on an older commit (5240d91 ("Removing legacy pub_ddr init code")). Then I rebased on top of master, which was 1865e8f ("storage: rpmb: call tee_fs_generate_fek() to generate FEK"). Since then, I could not reproduce the issue.

**Comment by JammyZhou** [comment] 2016-08-11 02:35
@wanchaoshan which commit were you running with? can you also try latest master as Jerome mentioned?

**Comment by jenswi-linaro** [comment] 2016-08-15 08:27
@jforissier, interesting, I wonder which commit fixed or hid the problem.

**Comment by jforissier** [comment] 2016-08-26 16:55
@jenswi-linaro FYI, I tried to reproduce the issue and bisect, by applying the final D02 patches on top of the older commit I mentioned above and rebasing master on top of that. It turns out that even with the earliest commit, I could not reproduce the assertion.

**Comment by jbech-optee-adm** [comment] 2016-09-15 21:41
Seems like this is working for most people and there hasn't been any discussion in about a month, so we're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Closed by jbech-optee-adm** 2016-09-15 21:41 UTC
