### ISSUE TITLE
make run error during OPTEE(QEMUv8) installation

### ISSUE THREAD

**Issue by fakhruddinbabor7** [OP-TEE/optee_os#5400] opened 2022-06-26 18:07 UTC
When Im trying to install opteee(QEMUv8) , at the last step when im giving "make run" command, im getting this following error:

running build_scripts
copying and adjusting /home/hira/optee-project/out-br/build/host-python3-3.9.7/Lib/smtpd.py -> build/scripts-3.9
copying and adjusting /home/hira/optee-project/out-br/build/host-python3-3.9.7/Tools/scripts/pydoc3 -> build/scripts-3.9
copying and adjusting /home/hira/optee-project/out-br/build/host-python3-3.9.7/Tools/scripts/2to3 -> build/scripts-3.9
changing mode of build/scripts-3.9/smtpd.py from 644 to 755
changing mode of build/scripts-3.9/pydoc3 from 644 to 755
changing mode of build/scripts-3.9/2to3 from 644 to 755
renaming build/scripts-3.9/smtpd.py to build/scripts-3.9/smtpd.py.9
renaming build/scripts-3.9/pydoc3 to build/scripts-3.9/pydoc3.9
renaming build/scripts-3.9/2to3 to build/scripts-3.9/2to3-3.9
make[2]: *** [package/pkg-generic.mk:305: /home/hira/optee-project/out-br/build/host-python3-3.9.7/.stamp_host_installed] Error 2
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory '/home/hira/optee-project/out-br'
make: *** [common.mk:342: buildroot] Error 2

Again when im giving "make run-only" command, im getting this error.

(qemu) qemu-system-aarch64: failed to load "Image"
make: *** [Makefile:429: run-only] Error 1

**Comment by jforissier** [comment] 2022-06-27 05:52
Duplicate of https://github.com/OP-TEE/build/issues/572.

**Closed by jforissier** 2022-06-27 05:52 UTC
