### ISSUE TITLE
TEE_ERROR_SIGNATURE_INVALID error of TEE_AsymmetricVerifyDigest()

### ISSUE THREAD

**Issue by Ubiquitous-BABA** [OP-TEE/optee_os#1329] opened 2017-01-30 18:29 UTC
Hi,
This is Hidenori BABA of Ubiquitous Corporation.  
I have a question about the TEE_AsymmetricVerifyDigest().

I have tested the TEE_AsymmetricVerifyDigest() using a test dataset which contains plaintext, public key and signature that was generated on Windows.  However, I got TEE_ERROR_SIGNATURE_INVALID error from TEE_AsymmetricVerifyDigest().

I think these test dataset is correct because I can get result of "Verified OK" with OpenSSL as follows.

```bash
# openssl dgst -sha1 -verify public-key-1024-windows.pem -signature sig_rsassa_pkcs1_sha1_1024_20B_Windows.dat plain_20B.dat
Verified OK
#
# openssl rsa -pubin -in public-key-1024-windows.pem -text -noout
Public-Key: (1024 bit)
Modulus:
    00:99:fd:2f:0b:46:ee:7f:34:50:fc:28:1e:6e:91:
    26:d1:cf:eb:6d:b0:cc:9c:49:13:35:ad:83:fc:a0:
    e4:71:62:1f:85:b1:d3:7e:ea:93:11:0b:ab:6a:84:
    76:25:72:44:eb:56:cf:49:71:2b:0a:e2:4a:54:08:
    bf:de:e4:b2:3a:9e:6d:ca:c5:eb:db:c0:89:ad:b1:
    cd:e9:f3:25:bc:0f:4e:91:90:a8:8a:f8:2f:5e:86:
    91:87:c6:66:2f:07:5b:d7:70:54:f3:f0:81:ce:b0:
    d0:bc:b1:1a:51:c2:c0:16:37:d2:26:8c:60:e0:58:
    a4:43:1f:4f:50:b6:30:60:af
Exponent: 65537 (0x10001)
#
```

I tested the following code.  Could you tell me, if incorrect usage of API?

Regards,
Hidenori

```c
uint8_t msg[] = {
    0x03, 0x78, 0x35, 0x64, 0x65, 0x0f, 0xfa, 0xb0,  0x6f, 0x59, 0x9c, 0x2b, 0xbd, 0x9d, 0x23, 0x9e,
    0x2b, 0xad, 0xd5, 0x86,
};

uint8_t rsa_modulus[] = {
    0x99, 0xfd, 0x2f, 0x0b, 0x46, 0xee, 0x7f, 0x34, 0x50, 0xfc, 0x28, 0x1e, 0x6e, 0x91, 0x26, 0xd1,
    0xcf, 0xeb, 0x6d, 0xb0, 0xcc, 0x9c, 0x49, 0x13, 0x35, 0xad, 0x83, 0xfc, 0xa0, 0xe4, 0x71, 0x62,
    0x1f, 0x85, 0xb1, 0xd3, 0x7e, 0xea, 0x93, 0x11, 0x0b, 0xab, 0x6a, 0x84, 0x76, 0x25, 0x72, 0x44,
    0xeb, 0x56, 0xcf, 0x49, 0x71, 0x2b, 0x0a, 0xe2, 0x4a, 0x54, 0x08, 0xbf, 0xde, 0xe4, 0xb2, 0x3a,
    0x9e, 0x6d, 0xca, 0xc5, 0xeb, 0xdb, 0xc0, 0x89, 0xad, 0xb1, 0xcd, 0xe9, 0xf3, 0x25, 0xbc, 0x0f,
    0x4e, 0x91, 0x90, 0xa8, 0x8a, 0xf8, 0x2f, 0x5e, 0x86, 0x91, 0x87, 0xc6, 0x66, 0x2f, 0x07, 0x5b,
    0xd7, 0x70, 0x54, 0xf3, 0xf0, 0x81, 0xce, 0xb0, 0xd0, 0xbc, 0xb1, 0x1a, 0x51, 0xc2, 0xc0, 0x16,
    0x37, 0xd2, 0x26, 0x8c, 0x60, 0xe0, 0x58, 0xa4, 0x43, 0x1f, 0x4f, 0x50, 0xb6, 0x30, 0x60, 0xaf,
};

uint8_t rsa_exponent[] = {
    0x01, 0x00, 0x01,
};

uint8_t sig[] = {
    0x72, 0xa8, 0x6a, 0xdc, 0x02, 0x94, 0xeb, 0x9f, 0x99, 0x44, 0x15, 0xf6, 0x9d, 0xb9, 0x72, 0xd4,
    0x0a, 0x4a, 0x65, 0x77, 0x63, 0x71, 0x18, 0x30, 0x65, 0x68, 0xab, 0x4f, 0x5b, 0x54, 0x56, 0x67,
    0xa7, 0x2d, 0xd3, 0xbc, 0x3e, 0x1a, 0xa9, 0x88, 0xa1, 0x50, 0x80, 0xf9, 0xe2, 0x19, 0x9a, 0x24,
    0x72, 0x57, 0xc1, 0xf9, 0xd1, 0x32, 0x11, 0x1e, 0x77, 0x5d, 0x82, 0x26, 0x69, 0x82, 0x4a, 0x3b,
    0x8d, 0x8f, 0x50, 0x49, 0x4f, 0x8c, 0xbe, 0x50, 0x49, 0x42, 0x2e, 0xa1, 0x21, 0x19, 0x7a, 0x75,
    0x0f, 0x55, 0x95, 0x1d, 0x53, 0x63, 0xc0, 0x02, 0x6f, 0x58, 0x04, 0x67, 0x96, 0xca, 0x93, 0xd9,
    0x16, 0x34, 0x5b, 0x31, 0x45, 0xf8, 0xcc, 0x07, 0x9e, 0x78, 0x9a, 0xca, 0x5d, 0xc0, 0x37, 0x71,
    0xb1, 0x90, 0xa2, 0xd6, 0x90, 0x35, 0xe8, 0x5a, 0xfd, 0x13, 0x4a, 0x23, 0x45, 0x79, 0x22, 0x20,
};

static TEE_Result rsa_verify_test(void)
{
    TEE_Result ret = TEE_ERROR_BAD_PARAMETERS;
    uint32_t algo;
    uint32_t len;
    uint32_t keylen;
    TEE_OperationHandle oh;
    TEE_ObjectHandle obj;
    TEE_Attribute key_attr[2];
    TEE_ObjectType type;

    keylen = 128;
    len = keylen * 8;

    algo = TEE_ALG_RSASSA_PKCS1_V1_5_SHA1;
    type = TEE_MODE_VERIFY;
    ret = TEE_AllocateOperation(&oh, algo, type, len);
    if(ret != TEE_SUCCESS) {
        EMSG("TEE_AllocateOperation: ret=%x, algo=%x, type=%x, len=%d", ret, algo, type, len);
        goto end;
    }

    type = TEE_TYPE_RSA_PUBLIC_KEY;
    key_attr[0].attributeID = TEE_ATTR_RSA_MODULUS;
    key_attr[0].content.ref.buffer = rsa_modulus;
    key_attr[0].content.ref.length = sizeof(rsa_modulus);
    key_attr[1].attributeID = TEE_ATTR_RSA_PUBLIC_EXPONENT;
    key_attr[1].content.ref.buffer = rsa_exponent;
    key_attr[1].content.ref.length = sizeof(rsa_exponent);
    ret = TEE_AllocateTransientObject(type, len, &obj);
    if (ret != TEE_SUCCESS) {
        EMSG("TEE_AllocateTransientObject: ret=%x, algo=%x, type=%x, len=%d", ret, algo, type, len);
        goto err1;
    }
    ret = TEE_PopulateTransientObject(obj, key_attr, 2);
    if (ret != TEE_SUCCESS) {
        EMSG("TEE_PopulateTransientObject: ret=%x, algo=%x, type=%x, len=%d", ret, algo, type, len);
        goto err2;
    }

    ret = TEE_SetOperationKey(oh, obj);
    if (ret != TEE_SUCCESS) {
        EMSG("TEE_SetOperationKey: ret=%x, algo=%x, type=%x, len=%d", ret, algo, type, len);
        goto err2;
    }

    ret = TEE_AsymmetricVerifyDigest(oh, NULL, 0, msg, sizeof(msg), sig, keylen);
    if (ret != TEE_SUCCESS) {
        EMSG("TEE_AsymmetricVerifyDigest: ret=%x", ret);
        goto err2;
    }

err2:
    TEE_FreeTransientObject(obj);
err1:
    TEE_FreeOperation(oh);
end:

    return TEE_SUCCESS;
}
```

**Comment by jforissier** [comment] 2017-02-03 10:26
Hi @Ubiquitous-BABA ,

Your code looks OK. I notice the modulus start with 00 in the openssl dump but there is no such 00 in `rsa_modulus[]`. Is it an openssl display thing?

**Comment by BabaH** [comment] 2017-02-03 12:32
Hi jforissier,

Thank you for your response.
Yes, it seems openssl adds 00 for dump with "-text" option because another openssl command doesn't add 00 as follows.

`# openssl rsa -pubin -inform PEM -in public-key-1024-windows.pem -noout -modulus
Modulus=99FD2F0B46EE7F3450FC281E6E9126D1CFEB6DB0CC9C491335AD83FCA0E471621F85B1D37EEA93110BAB6A8476257244EB56CF49712B0AE24A5408BFDEE4B23A9E6DCAC5EBDBC089ADB1CDE9F325BC0F4E9190A88AF82F5E869187C6662F075BD77054F3F081CEB0D0BCB11A51C2C01637D2268C60E058A4431F4F50B63060AF
#`

Also I found the following link for adding '00' of dump data.
  http://stackoverflow.com/a/17286288

**Comment by jbech-linaro** [comment] 2017-02-15 11:15
This was quite tricky to figure out, since I didn't know where you go the input from or how it was created (and the `msg` had the same size as the hash, which made me believe that this indeed was the hash).

But as the name of the function your calling (`TEE_AsymmetricVerifyDigest`), indicates that we are working with the digest of the plaintext (i.e, the hash and `SHA1` in your case).

So, you almost got it here. What you've missed is that for signature verification using `TEE_AsymmetricVerifyDigest` you operate on the **hash** of the message. I.e, so you'd need to make a hash of "`msg`" first. I did that manually outside the code and then replaced `msg` with the `sha1(msg)` instead. If you want to do that in the source code, then you can have a look [here](https://github.com/OP-TEE/optee_test/blob/ed00e1636c881f02026b8e8678f07d486d843312/host/xtest/xtest_4000.c#L3761-L3800).

So, with your code in our hello_world TA and then changed to:

```patch
diff --git a/ta/hello_world_ta.c b/ta/hello_world_ta.c
index 5e002ed..d03e553 100644
--- a/ta/hello_world_ta.c
+++ b/ta/hello_world_ta.c
@@ -92,11 +92,21 @@ void TA_CloseSessionEntryPoint(void __maybe_unused *sess_ctx)
 	DMSG("Goodbye!\n");
 }
 
+#if 0
 uint8_t msg[] = {
     0x03, 0x78, 0x35, 0x64, 0x65, 0x0f, 0xfa, 0xb0,  0x6f, 0x59, 0x9c, 0x2b, 0xbd, 0x9d, 0x23, 0x9e,
     0x2b, 0xad, 0xd5, 0x86,
 };
 
+    03 78 35 64 65 0f fa b0  6f 59 9c 2b bd 9d 23 9e 2b ad d5 86
+#endif
+
+// Hash of SHA-1 message
+uint8_t msg[] = {
+    0xb1, 0x2f, 0x0f, 0x65, 0x74, 0x35, 0x62, 0x22, 0x03, 0x29, 0xde, 0x42, 0xe1, 0x22, 0xa6, 0xdb,
+    0x1d, 0x90, 0x51, 0xa9
+};
+
 uint8_t rsa_modulus[] = {
     0x99, 0xfd, 0x2f, 0x0b, 0x46, 0xee, 0x7f, 0x34, 0x50, 0xfc, 0x28, 0x1e, 0x6e, 0x91, 0x26, 0xd1,
     0xcf, 0xeb, 0x6d, 0xb0, 0xcc, 0x9c, 0x49, 0x13, 0x35, 0xad, 0x83, 0xfc, 0xa0, 0xe4, 0x71, 0x62,
@@ -173,6 +183,8 @@ static TEE_Result rsa_verify_test(void)
     if (ret != TEE_SUCCESS) {
         EMSG("TEE_AsymmetricVerifyDigest: ret=%x", ret);
         goto err2;
+    } else {
+        DMSG("Successfully verified the signature!");
     }
 
 err2:
```

I get .... on the secure UART:
```bash
DEBUG:   USER-TA:rsa_verify_test:187: Successfully verified the signature!
```

I you're happy with this answer, would you mind close the issue?

// Joakim

**Comment by jbech-linaro** [comment] 2017-02-15 11:18
And here is a branch with the fix applied that you can test directly if you want to:
https://github.com/jbech-linaro/hello_world/commits/issue1329

**Comment by BabaH** [comment] 2017-02-15 15:20
Hi Joakim-san,

Thank you for your investigation.
I understood I need to generate digest of message when using TEE_AsymmetricVerifyDigest(). 

I confirmed my code with digest of original message.
Please close this issue.

Thank you for your cooperation.
Hidenori

**Closed** 2017-02-15 15:28 UTC
