### ISSUE TITLE
Creating new lib in optee-os: what are default_regular.o and default_bold.o ?

### ISSUE THREAD

**Issue by ppeiffer** [OP-TEE/optee_os#1466] opened 2017-04-05 17:10 UTC
Hi,

I'm adding my own lib under lib directory, let's say libtest
So:

1. I create directory lib/libtest and add my file (test.c)
2. I create a file lib/libtest/sub.mk which contains
srcs-y += test.c
3. I update ta/ta.mk by adding my lib
...
libname = test
libdir = lib/libtest
include mk/lib.mk
...

That works, but I noticed the my archive libtest.a contains also generated files libutee/tui/default_regular.o and libutee/tui/default_bold.o

Is it expected ?
If yes, what the purpose of these files ?

Thanks.

**Comment by jenswi-linaro** [comment] 2017-04-06 07:11
No this is unexpected behavior. Pull request https://github.com/OP-TEE/optee_os/pull/1467 should fix this.

**Comment by ppeiffer** [comment] 2017-04-06 11:40
Ok, thanks !

**Comment by jbech-optee-adm** [comment] 2017-04-26 11:31
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Closed by jbech-optee-adm** 2017-04-26 11:31 UTC
