### ISSUE TITLE
Problems trying to run xtest with OP-TEE + Android

### ISSUE THREAD

**Issue by jsherman3** [OP-TEE/optee_os#865] opened 2016-06-21 02:34 UTC
Hello,

I have successfully put AOSP + OP-TEE on the HiKey board and I'm currently trying to make an Android app that communicates with a TA.  I just connected UART3 to my computer and opened it up to see the serial output.  When Android loaded I tried running xtest to see if everything was working and I got this output: 
Used link: 
https://github.com/linaro-swg/optee_android_manifest
```
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# XTEST_TEE_TEST
#
######################################################
 
* XTEST_TEE_1001 Core self tests
ERR [2635] TEEC:TEEC_OpenSession:484: TEE_IOC_OPEN_SESSION failed
  XTEST_TEE_1001 OK
 
* XTEST_TEE_1004 Test User Crypt TA
ERR [2635] TEEC:TEEC_OpenSession:484: TEE_IOC_OPEN_SESSION failed
external/optee_test/host/xtest/xtest_1000.c:392: xtest_teec_open_session( &session, &crypt_user_ta_uuid, ((void*)0), &ret_orig) has an unexpected value: 0xffff0007 = TEEC_ERROR_BAD_STATE, expected 0x0 = TEEC_SUCCESS
  XTEST_TEE_1004 FAILED
 
* XTEST_TEE_1005 Many sessions
ERR [2635] TEEC:TEEC_OpenSession:484: TEE_IOC_OPEN_SESSION failed
external/optee_test/host/xtest/xtest_1000.c:445: xtest_teec_open_session(&sessions[i], &os_test_ta_uuid, ((void*)0), &ret_orig) has an unexpected value: 0xffff0007 = TEEC_ERROR_BAD_STATE, expected 0x0 = TEEC_SUCCESS
  XTEST_TEE_1005 FAILED
 
* XTEST_TEE_1006 Test Basic OS features
ERR [2635] TEEC:TEEC_OpenS[  541.900670] xtest[2635]: unhandled level 1 translation fault (11) at 0x00000000, esr 0x92000005
ession:484: TEE_[  541.910937] pgd = ffffffc04a659000
IOC_OPEN_SESSION[  541.915593] [00000000] *pgd=0000000000000000 failed
externa, *pud=0000000000000000l/optee_test/hos
t/xtest/xtest_10[  541.926070] 
00.c:462: xtest_[  541.928892] CPU: 1 PID: 2635 Comm: xtest Tainted: G        W       4.1.15-02393-g365a5d0 #1
teec_open_sessio[  541.938625] Hardware name: HiKey Development Board (DT)
n(&session, &os_[  541.945216] task: ffffffc074afb040 ti: ffffffc035124000 task.ti: ffffffc035124000
test_ta_uuid, (([  541.954074] PC is at 0x7fb7dec774
void*)0), &ret_o[  541.958755] LR is at 0x7fb7dec748
rig) has an unex[  541.963437] pc : [<0000007fb7dec774>] lr : [<0000007fb7dec748>] pstate: 20000000
pected value: 0x[  541.972224] sp : 0000007ffffff750
ffff0007 = TEEC_[  541.976930] x29: 0000007ffffff8e0 ERROR_BAD_STATE,x28: 0000007fb782e048  expected 0x0 = 
TEEC_SUCCESS
  [  541.986387] x27: 0000000000000004 XTEST_TEE_1006 Fx26: 0000007fb7831380 AILED
 
* XTES
T_TEE_1007 Test [  541.995853] x25: 00000055555c6490 Panic
ERR [2635x24: ed16657e732091f2 ] TEEC:TEEC_Open
Session:484: TEE[  542.005314] x23: 0000007ffffff818 _IOC_OPEN_SESSIOx22: 0000007ffffff8f8 N failed
extern
al/optee_test/ho[  542.014786] x21: 0000000000000000 st/xtest/xtest_1x20: 0000000000000000 000.c:484: xtest
_teec_open_sessi[  542.024257] x19: 0000007ffffff8f4 on(&session, &osx18: 00000000ffffffff _test_ta_uuid, (
(void*)0), &ret_[  542.033729] x17: 0000007fb7d36e50 orig) has an unex16: 0000007fb7deefa0 xpected value: 0
xffff0007 = TEEC[  542.043200] x15: 0000007fb7dc2f6c _ERROR_BAD_STATEx14: 54203d2030783020 , expected 0x0 =
 TEEC_SUCCESS
[  542.052672] x13: 6465746365707865 x12: 202c45544154535f 
[  542.059325] x11: 0000000000000000 x10: 0000000000004001 
[  542.064642] x9 : 0000000000000004 x8 : 0000000000000000 
[  542.069999] x7 : 0000000000000000 x6 : 000000000000003f 
[  542.075316] x5 : 0000000000000040 x4 : 0000000000000000 
[  542.080672] x3 : 0000000000000030 x2 : 0000007ffffff750 
[  542.086032] x1 : 000000008010a403 x0 : 0000000000000000 
[  542.091348] 
Segmentation fault
```
I checked /dev/tee* and had the following output:
`/dev/tee0 /dev/teepriv0
`
So the OP-TEE linux driver installed.  However when I run ps | grep supplicant, I get nothing.  So I think the tee-supplicant is not running.  Any insight on my problem?

**Comment by vchong** [comment] 2016-06-21 04:12
Have you tried running the supplicant first before running xtest?

```
$ tee-supplicant&
$ xtest
```

**Comment by jsherman3** [comment] 2016-06-21 04:14
Yes and when I ran tee-supplicant&
It said 
ERR [985] TEES:main:380: failed to find an OP-TEE supplicant device

**Comment by vchong** [comment] 2016-06-21 04:27
That should mean that it's already running.
Maybe ps on android is different.
Can you just run ps without the grep and see if you can see anything that resembles tee-supplicant?
If you do, then the problem is elsewhere, but it's hard to see what's happening with the logs all jumbled up. Can you try to run the commands over SSH, or on a different ADB session (via TCP maybe) so that only the crash is visible on the serial, and repost the crash?

**Comment by jsherman3** [comment] 2016-06-21 04:38
Oh should I be using xtest on the Android terminal? I was typing these commands on the serial terminal through the HiKey board

**Comment by jbech-linaro** [comment] 2016-06-21 06:29
@jsherman3 , @vchong , I'm pretty sure tee-supplicant isn't loaded. Firstly `ps | grep supplicant` says nothing. Secondly the print above, is typically seen when the TEE driver in kernel itself hasn't been loaded as it should. I think every time I've seen that, the cause has been that the firmware part in the device tree has been missing. Try for example `dmesg | grep optee`, if you get nothing there, then the driver hasn't been loaded correctly.

However, checking the instructions you've followed ([manifest.git](https://github.com/linaro-swg/optee_android_manifest/blob/master/optee.xml#L12-L13)), the Linux kernel branch in-use, it seems like it has the patch needed:
https://github.com/linaro-swg/linux/commit/5606f3f2746bdd5400f750a952e3363b8b9c98ac

So, not directly an answer, but to get somewhere, start with this:
1. Ensure that the driver has been loaded correctly, `dmesg | grep optee` should give you a couple of lines in the output.
2. When the driver is OK, continue with loading tee-supplicant.
3. When that is OK, try run xtest.

Regarding the terminal, it doesn't matter if you use the UART directly or `adb shell`, same same but different, both should work.

I'd like to help out more by setting it up and try it on my own, but I simply don't have time to do it right now.

**Comment by jsherman3** [comment] 2016-06-21 21:24
@jbech-linaro, Thank you for your reply.  I thought I followed the directions precisely, but then I remember this statement in the instructions:

In addition, you will need the pre-requisites necessary to build optee-os. Currently, the trusted firmware image is not built as part of these instructions. Please follow the instructions on https://github.com/OP-TEE/optee-os to build that platform for HiKey. This will generate a file arm-trusted-firmware/build/hikey/release/fip.bin that will be needed for flashing.
Was supposed to clone the repository for optee_os and build it for HiKey?  Because When I ran the Android instructions it created and flashed an fip.bin already for me.

**Comment by Lucasvo1** [comment] 2016-06-25 15:43
I had the same issue. I "solved" it by running tee-supplicant with sudo. Same goes for xtest.

**Comment by jsherman3** [comment] 2016-06-27 18:18
You ran this command from the HiKey Board? it's not allowing me to run sudo

**Comment by jbech-linaro** [comment] 2016-06-27 19:06
@jsherman3 , today just a couple of hours ago we released v2.1.0 of OP-TEE which has been verified on a variety of platforms (see the [changelog](https://github.com/OP-TEE/optee_os/blob/master/CHANGELOG.md#op-tee---version-210)). This release also covered the AOSP build you're trying to replicate, so having that said, it should work.

@d3zd3z in the preparation for this particular release, is this anything you have seen and if yes, do you know if there is a workaround for it?

**Comment by d3zd3z** [comment] 2016-06-27 19:50
I believe everything is covered in the README in the manifest repo. It is
easier to build than it was before, since the TAs are now built as part of
the Android build.

The kernel is still built as a separate step, and you will need to follow
the instructions to build optee_os for HiKey by itself in order to build
the trusted firmware image (fip.bin).

Test 1008 will fail unless /system is writable. You can do this with "adb
remount" from the host, or just ignore that particular failure.

David

**Comment by jsherman3** [comment] 2016-06-27 20:02
@d3zd3z, Thank you for your reply,
for clarification, I have to replace the prebuilt fip.bin that is in ./device/linaro/hikey with my fip.bin I build from source?

**Comment by d3zd3z** [comment] 2016-06-27 20:06
Yes. I've actually removed the prebuilt fip.bin from the
device/linaro/hikey in the linaro-swg repo. It is kind of picky about
versioning between the trusted OS and the TAs built as part of the Android
build, so for now, people should just build the fip.bin themselves.

David

**Comment by jsherman3** [comment] 2016-06-27 20:13
When I'm running Android and I'm looking at the boot log. I usually push cntrl+C to get to the console so I can run xtest, would this cause an issue?

**Comment by d3zd3z** [comment] 2016-06-27 20:19
I wouldn't expect it to be necessary to press Ctrl-C. Have you tried just pressing enter. It prints a shell prompt, and then several other things print messages out, hiding the prompt.

I usually start tee supplicant from the console:
```
$ su
# tee-supplicant &
```
and then run xtest from an adb shell. But, you can also just run xtest from the console.

**Comment by jsherman3** [comment] 2016-06-27 20:24
When I installed just regular OP-TEE it had press ENTER to activate console, but for AOSP it gives me the boot log and never gets to the point where it says press ENTER to activate console

**Comment by d3zd3z** [comment] 2016-06-27 21:16
It doesn't tell you to press enter. It should just give you a prompt, but
it gets obscured by additional messages. You should still be able to just
press enter.

**Comment by jbech-optee-adm** [comment] 2016-06-29 08:13
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Closed by jbech-optee-adm** 2016-06-29 08:13 UTC
