### ISSUE TITLE
when testing optee os with arm trusted firmware (I utilized optee os tee.bin as bl32 image) on juno platform, I got an error

### ISSUE THREAD

**Issue by diamond001** [OP-TEE/optee_os#149] opened 2014-12-08 06:00 UTC
when I tested optee os with arm trusted firmware (I utilized optee os tee.bin as bl32 image) on juno platform, I got an error:
 INFO: Using FIP
 INFO: Loading file 'bl32.bin' at address 0x4023000
 WARNING: Failed to reserve memory: 0x4023000 - 0x407e540
 INFO: Trying to load image at address 0x4023000, size = 0x5b540
 INFO: Current memory layout:
 INFO: total region = [0x4023000, 0x4040000]
 INFO: free region = [0x4023000, 0x4040000]
 WARNING: Failed to load BL3-2 (-12)

I found that tee.bin is 172K, but the tzram free space for bl32 is 64K (./plat/juno/include/platform_def.h), it's smaller than the requested size. 
 I tried to modify the size of tzram for bl32, but the atf stop at the beginning of bl2:

VERBOSE: Reserved 12288 bytes (discarded 0 bytes below)
 INFO: BL1: 0x4001000 - 0x4004000 [size = 12288] -- hugo -002
 NOTICE: Booting Trusted Firmware
 NOTICE: BL1: v1.0(debug):bbb59e7
 NOTICE: BL1: Built : 16:28:51, Dec 5 2014
 INFO: BL1: RAM 0x4001000 - 0x4004000
 VERBOSE: FIP header looks OK.
 INFO: Using FIP
 INFO: Loading file 'bl2.bin' at address 0x4053000
 VERBOSE: Reserved 53248 bytes (discarded 32760 bytes above)
 INFO: File 'bl2.bin' loaded: 0x4053000 - 0x4058008
 VERBOSE: Reserved 12288 bytes (discarded 0 bytes below)
 NOTICE: BL1: Booting BL2
 INFO: BL1: BL2 address = 0x4053000
 INFO: BL1: BL2 spsr = 0x3c5
 VERBOSE: BL1: BL2 memory layout address = 0x4004000

Could you please tell me how to solve this problem?

**Comment by hwithaar** [comment] 2015-03-04 07:08
I had the same issue and now work with the 'old' version.
When will this be fixed in a later version?

**Comment by jenswi-linaro** [comment] 2015-03-04 07:47
The problem is that ARM-TF doesn't have generic support to load partitioned binaries. The current patch is a temporary solution that also gives a good example of what we need to load OP-TEE.

I've discussed this with one of the ARM-TF engineers and some generic support for loading partitioned binaries will be added. Once that's in place we'll prepare new OP-TEE patches which we'll try to get merged into ARM-TF.

**Comment by pascal-brand-st** [comment] 2015-06-23 06:58
Related to https://github.com/ARM-software/tf-issues/issues/301, still to be resolved

**Closed by pascal-brand-st** 2015-06-23 06:58 UTC
