### ISSUE TITLE
readelf: Warning: Corrupt ARM compact model table entry:

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#1193] opened 2016-11-22 12:34 UTC
I found that when I add use read32 in a function ,I met this warning.
```
readelf: Warning: Corrupt ARM compact model table entry: e5901104 
readelf: Warning: Unknown ARM compact model index encountered
```
Has anyone met this?

**Comment by etienne-lms** [comment] 2016-11-25 16:34
hi @MrVan , there are already lots of use of read32 in the optee core. no build issue.
strange you face such issues.

**Comment by jforissier** [comment] 2016-11-25 16:39
I've never seen these warnings myself. Could it be caused by a corrupt object file? Try re-building from scratch (delete the output directory). Or perhaps you reached some kind of size limitation?
Does the binary work despite the warnings?

**Comment by jbech-linaro** [comment] 2017-02-15 17:26
@MrVan, any update? Seems like you're "alone" facing this issue. If the issue has been resolved, I'd like to close this issue (I'm trying to clean up in our open issues).

**Closed** 2017-02-16 00:36 UTC
