### ISSUE TITLE
Issue while using TEEC_RegisterSharedMemory & TEEC_AllocateSharedMemory together

### ISSUE THREAD

**Issue by niteshnarayanlal** [OP-TEE/optee_os#754] opened 2016-04-22 06:54 UTC
I have a TA & Host application which was working fine with the release 1.0.0, but with latest release 2.0.0 its not.
TA is not able to exchange processed data to host beyond a certain buffer length (18 bytes).
In our host application source, we have used both TEEC_RegisterSharedMemory & TEEC_AllocateSharedMemory. 
Surprisingly everything restored to normal as I removed TEEC_RegisterSharedMemory with optee-2.0.0. 
I am wondering how this approach was working release optee_os -1.0.0?

**Comment by pascal-brand-st-dev** [comment] 2016-04-22 07:46
Do you think you can create a unit test that reproduces this issue so that we can investigate? The best would to have a new xtest added in https://githhub.com/OP-TEE/optee_test

**Comment by niteshnarayanlal** [comment] 2016-04-28 06:52
Sorry for the delay in response, I will prepare a unit case as I find some time and get back to you.

**Comment by jbech-linaro** [comment] 2016-06-03 10:54
@niteshnarayanlal can you check whether this still is an issue? Another [issue](https://github.com/OP-TEE/optee_os/issues/788) referred to this issue and there has been a fixed created since then.

**Comment by niteshnarayanlal** [comment] 2016-06-03 13:18
Thanks for the update, but it will be difficult for me to try this right away.
I will update in case I face this issue, when I try.
Till then I think we may either put this on hold or even close it.

**Comment by jbech-optee-adm** [comment] 2016-06-29 08:28
OP-TEE 2.1.0 was released yesterday and was tested OK on all platforms in our possession. Based on that and the previous comment from you I've decided to close this issue. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Closed by jbech-optee-adm** 2016-06-29 08:28 UTC
