### ISSUE TITLE
TEE_CreatePersistentObject Panic Issue

### ISSUE THREAD

**Issue by MannyWang** [OP-TEE/optee_os#1311] opened 2017-01-24 06:11 UTC
Hello, everyone.
I'm a tee newer.
I want to encrypt file with Secure Storage API.
It's work at op-tee v2.1.0, but v2.3.0 is not.

This's my code.
```c
char oms_rsa_keypair_id[] = "oms_rsa_keypair_object_id";
                                                                                                                                                                   
ret = TEE_AllocateTransientObject(TEE_TYPE_RSA_KEYPAIR, BYTES2BITS(SIZE_RSA_MODULO), &rsa_keypair);                                                                                                                      

ret = TEE_GenerateKey(rsa_keypair, BYTES2BITS(SIZE_RSA_MODULO), NULL, 0);                                                                                                                             

ret = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE,
                                            oms_rsa_keypair_id, sizeof(oms_rsa_keypair_id),
                                            0, rsa_keypair, 0, 0, &oms_RSA_keypair_object);
```

The Error Message in TA.
```bash
[ta log] utee_storage_obj_create result : ffff0006 <---------------tee_api_objects.c
ERROR:   USER-TA: Panic 0x0[
ERROR:   TEE-CORE: TA panicked with code 0x0 usr_sp 0x40000fb0 usr_lr 0x0
```

somebody have same issue？

**Comment by lws-team** [comment] 2017-01-24 08:40
Does the panic come after TEE_CreatePeristentObject() returns, ie later in your code?

How about put `return 0;` immediately after the call to TEE_CreatePeristentObject() and see if the panic is gone.

**Comment by MannyWang** [comment] 2017-01-24 09:04
@lws-team 

This is a complete code.
```
TEE_Result TA_CreateEntryPoint(void)
{
        char oms_rsa_keypair_id[] = "oms_rsa_keypair_object_id";
        TEE_ObjectHandle rsa_keypair = NULL;
        TEE_Result ret = TEE_SUCCESS;

        ret = TEE_OpenPersistentObject(TEE_STORAGE_PRIVATE,
                                          oms_rsa_keypair_id, sizeof(oms_rsa_keypair_id),
                                          0, &oms_RSA_keypair_object);
        if (ret == TEE_SUCCESS) {
                EMSG("RSA key exist");
                return ret;
        } else if (ret == TEE_ERROR_ITEM_NOT_FOUND) {
                EMSG("RSA key need to be created");
        } else {
                EMSG("TEE_OpenPersistentObject failed: 0x%x", ret);
                return ret;
        }

        ret = TEE_AllocateTransientObject(TEE_TYPE_RSA_KEYPAIR,
                                             BYTES2BITS(SIZE_RSA_MODULO), &rsa_keypair);
        if (ret != TEE_SUCCESS) {
                EMSG("TEE_AllocateTransientObject failed : 0x%x", ret);
                goto out;
        }

        ret = TEE_GenerateKey(rsa_keypair, BYTES2BITS(SIZE_RSA_MODULO), NULL, 0);
        if (ret != TEE_SUCCESS) {
                EMSG("TEE_GenerateKey failed : 0x%x", ret);
                goto out;
        }

        ret = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE,
                                            oms_rsa_keypair_id, sizeof(oms_rsa_keypair_id),
                                            0, rsa_keypair, oms_rsa_keypair_id, sizeof(oms_rsa_keypair_id), &oms_RSA_keypair_object);
        return 0;

        if (ret != TEE_SUCCESS)
                EMSG("TEE_CreatePersistentObject failed : 0x%x", ret);
out:
        TEE_FreeTransientObject(rsa_keypair);
        return ret;
}
```
The panic happened in TEE_CreatePersistentObject(). So it is not execute after TEE_CreatePersistentObject(), ex.TEE_FreeTransientObject(rsa_keypair).

**Comment by lws-team** [comment] 2017-01-27 04:21
Have you tried deleting your /data?  It seems this api is a bit too willing to panic rather than just return an error.

**Comment by lws-team** [comment] 2017-01-27 04:28
To elaborate... in lib/libutee/tee_api_objects.c for CreatePersistentObject

```
err:
        if (object)
                *object = TEE_HANDLE_NULL;
        if (res == TEE_ERROR_ITEM_NOT_FOUND ||
            res == TEE_ERROR_ACCESS_CONFLICT ||
            res == TEE_ERROR_OUT_OF_MEMORY ||
            res == TEE_ERROR_STORAGE_NO_SPACE ||
            res == TEE_ERROR_CORRUPT_OBJECT ||
            res == TEE_ERROR_STORAGE_NOT_AVAILABLE)
                return res;

        TEE_Panic(0);
```

This pattern is prone to trouble if the functions it calls or that those call grow some new error cases.  Even earlier in the same function

```
        if (objectIDLen > TEE_OBJECT_ID_MAX_LEN) {
                res = TEE_ERROR_BAD_PARAMETERS;
                goto err;
        }
```

That is elevated to a panic instead of a failure return.

It received a TEE_ERROR_GENERIC from something it called ... elevated to a panic by this.

In release mode panics are almost completely silent with no backtrace.... I enabled unwinding a while back but never got a backtrace.

Maybe TEE_Panic() should always issue __FILE__ and __LINE__...

**Comment by jforissier** [comment] 2017-01-27 09:21
> To elaborate... in lib/libutee/tee_api_objects.c for CreatePersistentObject
> 
> ```
> err:
>         if (object)
>                 *object = TEE_HANDLE_NULL;
>         if (res == TEE_ERROR_ITEM_NOT_FOUND ||
>             res == TEE_ERROR_ACCESS_CONFLICT ||
>             res == TEE_ERROR_OUT_OF_MEMORY ||
>             res == TEE_ERROR_STORAGE_NO_SPACE ||
>             res == TEE_ERROR_CORRUPT_OBJECT ||
>             res == TEE_ERROR_STORAGE_NOT_AVAILABLE)
>                 return res;
> 
>         TEE_Panic(0);
> ```
> 
> This pattern is prone to trouble if the functions it calls or that those call grow some new error cases. 

That's exactly what the GP spec mandates (GP Internal Core API v1.1 section 5.7.2, "Return Code"). I don't see how we could make this better... except we could (should?) use `res` as a argument to `TEE_Panic()`. I don't see the reason why we call `TEE_Panic()` with 0 most of the time.

☞ Any opinion on this? I can fix this if we agree.

> Even earlier in the same function
> 
> ```
>         if (objectIDLen > TEE_OBJECT_ID_MAX_LEN) {
>                 res = TEE_ERROR_BAD_PARAMETERS;
>                 goto err;
>         }
> ```
> 
> That is elevated to a panic instead of a failure return.

That is the expected behavior...

> 
> It received a TEE_ERROR_GENERIC from something it called ... elevated to a panic by this.

Same.

> In release mode panics are almost completely silent with no backtrace.... I enabled unwinding a while back but never got a backtrace.

That's because unwinding of user-mode code is not implemented. Only kernel ("TEE core") code can be unwound.
So, you will get a stack dump if an exception occurs in the TEE core, or if it calls `panic()`[1], provided that CFG_CORE_UNWIND=y (which is the case when CFG_TEE_CORE_DEBUG=y).
But no dump if the TA crashes or panics.

[1] Note that `panic()` in TEE core is different than `TEE_Panic()` in a TA. The latter will stop the application, the former will crash the whole TEE.

> 
> Maybe TEE_Panic() should always issue __FILE__ and __LINE__...

`TEE_Panic()` uses `EMSG()` so it will issue `__func__` and `__LINE__` if the "long message" level is appropriate. Set `CFG_MSG_LONG_PREFIX_THRESHOLD=1` and you will see for instance:
```
$ xtest 9230
* regression_9230 50-17-5a
ERROR:   USER-TA:TEE_SetOperationKey:586: Panic 0x0
```
... instead of:
```
$ xtest 9230
* regression_9230 50-17-5a
ERROR:   USER-TA: Panic 0x0

```

☞ What we could do is, if the trace level is set to _DEBUG or _FLOW, we show the full prefix whatever the severity. Because it means we're in debug mode with lots of output already. I can also cook up a patch for this.

As for `__FILE__`, indeed it is not used in the debug output, which I find a bit inconvenient.
☞ Should we print `__FILE__`:`__LINE__`:`__func__` instead?

**Comment by lws-team** [comment] 2017-01-27 10:26
> That's exactly what the GP spec mandates (GP Internal Core API v1.1 section 5.7.2, "Return Code"). I don't see how we could make this better... except we could (should?) use res as a argument to TEE_Panic(). I don't see the reason why we call TEE_Panic() with 0 most of the time.

Mmm well, there is not much you can do about it then.  Yes capturing `res` in the panic reason makes sense, although I see other places in my travels that destroy res by "summarizing" it as GENERIC if not success, that's not helping either; maybe also mandatory.

At the minute in the example I gave

```
        res = TEE_ERROR_BAD_PARAMETERS;
```

res gets set and then discarded by the panic(0) that makes no sense.  So yes it should tell us res in hex.

CFG_MSG_LONG_PREFIX_THRESHOLD=1 should be globally on, atm when you see "there was a panic for reason $NOREASON" it "brings on a feeling of despondency".  I guess it is what you might want in production but nobody can go straight to production with this.  There are many ways to get to a panic like filename too long, which the user would normally expect to be an -ETOOLONG type job.  So few users will be able to avoid being faced with a panic at some point.  If there is absolutely no useful info shown it is the user who panics.

> Should we print __FILE__:__LINE__:__func__ instead?

Yes adding `__FILE__` also sounds like it's going to help.  Presumably gcc just stores `const char *` with same content once, so this shouldn't be too much bloat.

> What we could do is, if the trace level is set to _DEBUG or _FLOW, we show the full prefix whatever the severity. Because it means we're in debug mode with lots of output already. I can also cook up a patch for this.

I think panic is a bit different, unless you enabled some really big release switch, you want the panic coordinates on ANY panic that comes up, whether or not you thought you were debugging it.

If no backtrace context, that is painful to reconstruct (I spent the afternoon tracing my problem like that) but it is invaluable to have the coordinates of the actual panic anyway... I hacked it in to print the file and line every time here.

I still can't find my problem... using REE FS Open works but Create comes back from RPC with GENERIC...

**Comment by lws-team** [comment] 2017-01-28 04:06
Here is an example of simply adhering to the standard giving bad results...

```
static TEEC_Result ree_fs_new_create(size_t num_params,
				     struct tee_ioctl_param *params)
{
	char abs_filename[PATH_MAX];
	char abs_dir[PATH_MAX];
	char *fname;
	char *d;
	int fd;
	const int flags = O_RDWR | O_CREAT | O_TRUNC;

	if (num_params != 3 ||
	    (params[0].attr & TEE_IOCTL_PARAM_ATTR_TYPE_MASK) !=
			TEE_IOCTL_PARAM_ATTR_TYPE_VALUE_INPUT ||
	    (params[1].attr & TEE_IOCTL_PARAM_ATTR_TYPE_MASK) !=
			TEE_IOCTL_PARAM_ATTR_TYPE_MEMREF_INPUT ||
	    (params[2].attr & TEE_IOCTL_PARAM_ATTR_TYPE_MASK) !=
			TEE_IOCTL_PARAM_ATTR_TYPE_VALUE_OUTPUT)
		return TEEC_ERROR_BAD_PARAMETERS;

	fname = tee_supp_param_to_va(params + 1);
	if (!fname)
		return TEEC_ERROR_BAD_PARAMETERS;

	if (!tee_fs_get_absolute_filename(fname, abs_filename,
					  sizeof(abs_filename)))
		return TEEC_ERROR_BAD_PARAMETERS;

	fd = open_wrapper(abs_filename, flags);
	if (fd >= 0)
		goto out;
	if (errno != ENOENT)
		return TEEC_ERROR_GENERIC;

	/* Directory for file missing, try make to it */
	strncpy(abs_dir, abs_filename, sizeof(abs_dir));
	abs_dir[sizeof(abs_dir) - 1] = '\0';
	d = dirname(abs_dir);
	if (!mkdir(d, S_IRUSR | S_IWUSR | S_IXUSR)) {
		fd = open_wrapper(abs_filename, flags);
		if (fd >= 0)
			goto out;
		/*
		 * The directory was made but the file could still not be
		 * created.
		 */
		rmdir(d);
		return TEEC_ERROR_GENERIC;
	}
	if (errno != ENOENT)
		return TEEC_ERROR_GENERIC;

	/* Parent directory for file missing, try to make it */
	d = dirname(d);
	if (mkdir(d, S_IRUSR | S_IWUSR | S_IXUSR))
		return TEEC_ERROR_GENERIC;

	/* Try to make directory for file again */
	strncpy(abs_dir, abs_filename, sizeof(abs_dir));
	abs_dir[sizeof(abs_dir) - 1] = '\0';
	d = dirname(abs_dir);
	if (mkdir(d, S_IRUSR | S_IWUSR | S_IXUSR)) {
		d = dirname(d);
		rmdir(d);
		return TEEC_ERROR_GENERIC;
	}

	fd = open_wrapper(abs_filename, flags);
	if (fd < 0) {
		rmdir(d);
		d = dirname(d);
		rmdir(d);
		return TEEC_ERROR_GENERIC;
	}

out:
	params[2].u.value.a = fd;
	return TEEC_SUCCESS;
}

static TEEC_Result ree_fs_new_close(size_t num_params,
				    struct tee_ioctl_param *params)
{
	int fd;

	if (num_params != 1 ||
	    (params[0].attr & TEE_IOCTL_PARAM_ATTR_TYPE_MASK) !=
			TEE_IOCTL_PARAM_ATTR_TYPE_VALUE_INPUT)
		return TEEC_ERROR_BAD_PARAMETERS;

	fd = params[0].u.value.b;
	while (close(fd)) {
		if (errno != EINTR)
			return TEEC_ERROR_GENERIC;
	}
	return TEEC_SUCCESS;
}
```

I assume the standard is saying 'if problems other than xxx, return GENERIC", which is what the code is doing.

But the code is also repeatedly throwing away the critical information to understand and debug the problem.  I think we can agree this isn't a Good Way.

In my case after I drill down to the failing posix api, I see the errno is 30, telling me the fs is read-only.  If the panic had said "errno 30" somewhere, I would have some extra hours of life for free.  (I will open a separate issue to discuss RO TEE /data FS).

It'd be nice if we could do something like extend the type of "internal" TEE_Result to be uint64_t.... for example all this code in `tee-supplicant/src/tee_supp_fs.c` is not having to use TEE_Result type directly IIUI it could all use TEE_ResultInternal or something, which is a uint64_t truncated to TEE_Result back in Secure World apis.

If so you could stash auxiliary error info like errno in the upper 32 bits.  Where errno is meaningful, you do something like `return MAKE_TEE_RESULT(errno, TEEC_ERROR_GENERIC);`  When errno is not meaningful, setting the uint64_t return type to the existing standard constants as it is now, like `return TEEC_ERROR_GENERIC;` also zeros the upper uint32_t indicating no valid info there and works fine.

**Comment by TW-MannyWang** [comment] 2017-02-02 02:06
@lws-team I'm very very appreciate, and thank you very much for your suggestion.

Because I'm a newer at OP-TEE. I should figure Secure Storage out, so I want to read the GP document first.

I don't like to waste your time for the unknown issue I asked.

Thank you ^^

**Comment by lws-team** [comment] 2017-02-02 03:23
Well you are welcome.  But there's clearly bigger problems in the OP-TEE implementation atm.

Devaluing the error checking by just overwriting and ignoring errno detail naturally leads to evil like, eg, ignoring return codes altogether from Posix apis like rmdir() - "cos it will get thrown away anyway" - as you can see in the section I pasted above.

**Comment by vchong** [comment] 2017-02-02 03:45
fyi https://github.com/OP-TEE/optee_os/pull/1328 was merged 2 days ago to capture `res`.

**Comment by lws-team** [comment] 2017-02-02 03:51
@vchong it's certainly an improvement over every panic just saying panic(0).

But eg, errno is not captured.  errno is required to interpret what actually happened for many Posix apis, since they just return -1 if probs and have the reason in errno.  You can see how many different reasons there are in the code I quoted above it will return only GENERIC in res and in the panic(), which part of the sequential code blew is lost and the reason it blew is lost.  In some cases the api returns are not even checked.

It's meeting the minimum requirements of the standard I guess, but it's quite hostile code actually if something goes wrong.

**Comment by jbech-linaro** [comment] 2017-02-15 18:11
All involved in this thread. We've seen the comments related to return codes and we'll eventually pick it up and improve it in the future. Thanks for the suggestions.

The initial question and issue has been answer and resolved and therefore I'm going to close this issue. If you however have follow-up questions feel free to re-open the issue.

**Closed** 2017-02-15 18:11 UTC
