### ISSUE TITLE
Build optee_os for QEMU can't login in normal world terminal

### ISSUE THREAD

**Issue by zx08uestc** [OP-TEE/optee_os#1103] opened 2016-10-11 02:17 UTC
hi,everyone

```
  I follow the instruction to build op-tee for QEMU, and I succeed execute all instructions, after I execute the command "make all run", it does open QEMU, after I execute ‘c' then <enter> ,the normal world and secure world have started,but when execute over, I can't enter into normal world terminal.
 I stop in this:
```

![qq 20161011100917](https://cloud.githubusercontent.com/assets/5203778/19256688/f23f5290-8f9b-11e6-922f-88919150a2ff.jpg)

```
 Does anybody can help me,
 My Ubuntu version is 14.04 LTS , I use vmware for ubuntu run in windows 7
 Thanks  a lot
```

**Comment by jenswi-linaro** [comment] 2016-10-11 05:43
It looks like you're affected by a recent regression in QEMU. Try to use the latest OP-TEE release instead, there we've selected a version of QEMU that doesn't have this regression.

**Comment by zx08uestc** [comment] 2016-10-11 07:50
Thank you for the replay，I find that when I fellow the instructions,execute "repo sync" ,It may
be missing some files, so I search the Internet, execute repo init again, but this time I execute "repo init -u https://github.com/OP-TEE/manifest.git -m default.xml --repo-url=git://codeaurora.org/tools/repo.git". The Other is the same as the instruction. It does work.

**Comment by aj700** [comment] 2016-10-27 12:12
had same issue. Switching to stable manifest(qemu_v8_stable.xml) helped me as per Jens comment solved it.

**Comment by jbech-linaro** [comment] 2016-10-27 12:25
**For QEMUv7**: Actually, both latest on QEMU and the stable 2.2.0 release are both currently using a tagged revision of QEMU because of the regression in .. QEMU. So, latest **is** working fine, that is what I'm using. Try some cleaning.
```
$ cd qemu && git clean -xdf
$ cd .. && repo sync -d
$ cd build && make all
```
And it will probably work.

**For QEMUv8**: Arun is right, there we haven't set the tagged QEMU version and therefore you must as of now use the stable release (`qemu_v8_stable.xml`) until the fix has been upstreamed (or you have to go into the `qemu` folder and manually check  the working commit out -> `$ git checkout c5d128ffeb5357df1ea3e6de0c13b3d6a09f6064`). If someone would like to, please feel free to submit a temporary fix for `qemu_v8_stable.xml` containing the commit just mentioned.

**Comment by jbech-optee-adm** [comment] 2016-11-03 09:02
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Closed by jbech-optee-adm** 2016-11-03 09:02 UTC
