### ISSUE TITLE
xtest hung when tee-supplicant not run

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_os#922] opened 2016-07-15 10:42 UTC
In the last version, xtest hung when tee-supplicant not run, then kernel will panic.
I think it should exit or can be interrupted by 'ctrl+c' when tee-supplicant not run.

In previous version, it will print follow information and then exit.
    "shm service not available"

It is easy to reproduce with FVP.

**Comment by sorenb-xlnx** [comment] 2016-07-15 13:37
I experience the same problem on ZynqMP when I forget to start the tee-supplicant.

**Comment by jbech-linaro** [comment] 2016-07-15 14:05
Indeed, this seems like a bug that needs to be fixed. Without digging into it I think what is happening is that xtest first do the self tests, that goes well. Then it tries to load the Crypt TA by sending a RPC message to normal world, but the RPC message just (incorrectly) hangs somewhere because it finds no tee-supplicant to talk to.

@jenswi-linaro, related somewhere back in my head I think I remember a discussion with Arnd, Laura etc regarding auto-loading tee-supplicant? Did we have such a discussion? Did it lead somewhere?

**Comment by jbech-linaro** [comment] 2016-07-16 19:14
It is hanging waiting for an answer from tee-supplicant in [optee_supp_thrd_req](https://github.com/linaro-swg/linux/blob/optee/drivers/tee/optee/supp.c#L78). I think there is a deadlock between this and the code in `optee_supp_recv`. Can it be solved by checking the `supp.available`?

**Comment by zhupg** [comment] 2016-07-18 03:21
I have done the test, check "supp.available" in function optee_open_session().
It will not hang. 
Mostly the xtest return a error and exit, or segmentation falt(such as test 1007).

I think it is a solution, but maybe it is better to resolve the deadlock.

**Comment by jenswi-linaro** [comment] 2016-07-18 10:17
I think we should consider it a requirement on the system to have tee-supplicant running. To improve the user experience when tee-supplicant isn't running we could either let the call timeout with a very long timeout (I'm talking about minutes here) or allow the wait to be interrupted.

Tee-supplicant can be auto-started based on a uevent emitted with the driver is instantiated.

The reason I'd like to wait for tee-supplicant to become available instead of aborting is if something during boot uses a TA it will quickly be quite messy for user space to determine when it's safe to call the TA (consider different drivers with different supplicants etc).

**Comment by jforissier** [comment] 2016-07-18 10:49
+1 for waiting for tee-supplicant to become available. IMO interruptible sleep is the best option (most user-friendly).

**Comment by zhupg** [comment] 2016-07-18 10:53
Dear jenswi：
    agree with you.
    Waiting for tee-supplicant and can be interrupted will have a better user experience.

**Comment by jenswi-linaro** [comment] 2016-07-18 13:42
Please review fix in https://github.com/linaro-swg/linux/pull/18

**Comment by zhupg** [comment] 2016-07-22 02:25
review+1, thanks.

Should I close this issue?

**Comment by jbech-linaro** [comment] 2016-07-22 12:58
Yes @zhupg , please close the issue now, since a fix has been merged. Thanks for reporting!

**Closed** 2016-07-28 02:04 UTC
Labels: bug

**Comment by lws-team** [comment] 2017-01-03 23:32
Tee-supplicant running -> xtest runs and completes no errors.

No tee-supplicant ->

```
# xtest 
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# XTEST_TEE_TEST
#
######################################################
 
* XTEST_TEE_1001 Core self tests
  XTEST_TEE_1001 OK
 
* XTEST_TEE_1004 Test User Crypt TA
(stalled silently)
^C
#
```
It is no longer hung.  But shouldn't it print something like "waiting for tee-supplicant", or perhaps "No tee-supplicant" and exit since these should not normally race each other?

**Comment by jenswi-linaro** [comment] 2017-01-04 07:09
I can see two ways to do this.
1. Assume that undue delays while invoking secure world from xtest is due to tee-supplicant not  being available and just print something in xtest.
2. Have a timeout on the semaphore on which we're waiting for the supplicant to respond and print something from the driver.

I'm not particular exited about either of them. 1 take care of the user experience when running xtest. In 2 we'll have to hard code a value for what we consider a timeout that works in all situations.

**Comment by lws-team** [comment] 2017-01-04 07:40
You only really need to take care about the first guy calling into optee, because if he gets past that there is no problem.

You can also have alarm(2) that is cancelled after the first test that depends on tee-supplicant completes... at least on Linux.

I agree it's a bit messy but maybe it's nice for host apps if libteec looks after this.

**Comment by jenswi-linaro** [comment] 2017-01-04 08:10
Alarm(2) isn't really an option unless we want to abort the syscall and return an error as the syscall can't just be restarted. Then there's also the issue that alarm(2) may already be in active use by the application.

Some calls can take a long time to complete without being an error so a it's not easy to detect an unavailable tee-supplicant in a generic reliable way from libteec.

**Comment by etienne-lms** [comment] 2017-01-04 10:49
If the issue is about xtest user experience, maybe we could find a way for xtest to check whether a supplicant is running ? For example trying to open the `/dev/teeprivX` related to the `/dev/teeX`: a successful open shows no supplicant already registered to optee driver. This test should be kept in xtest, for optee tester convenience only.

Note that one can use optee without supplicant: no TA loaded from linux world, no secure storage, no "delay"... So it is even harder for libteec to know whether or not the tee-supplicant is required.

**Comment by jenswi-linaro** [comment] 2017-01-04 10:59
Maybe it's enough to check if there's a process called "tee-supplicant" running or not from xtest?

**Comment by etienne-lms** [comment] 2017-01-04 11:01
@jenswi-linaro, true. what's the easiest the maintain?

**Comment by lws-team** [comment] 2017-01-04 11:06
Turning it on its head a bit... how about libteec becomes the guy who starts tee-supplicant in a fork as soon as someone asks it to do something that requires it?  libteec is the only guy who directly requires tee-supplicant if I understood it.

**Comment by jenswi-linaro** [comment] 2017-01-04 12:09
No, tee-supplicant should be started via init scripts or similar with correct uid etc. We don't want a suid binary. Apart from that there could be clients to secure world in the kernel too.

**Comment by jenswi-linaro** [comment] 2017-01-04 12:10
@etienne-lms, just looking for a process with a specific name has to be very easy to implement and maintain.
