### ISSUE TITLE
file saving in OPTEE failed

### ISSUE THREAD

**Issue by ggao-inven** [OP-TEE/optee_os#1516] opened 2017-05-10 04:02 UTC
Hi,
  I am experiencing a problem that file saving problem. It seems when the file is large and file is divided into 50 files, each file is 4K in size. If I use iterator, it will panic. I can see the directory contains block0.1, block1.0...block44.0, block45.0.  Then I use a enumerator and it crashes.
The error code is "TA panicked with code 0x0 usr_sp 0x40014610 usr_lr 0x400914bb"

 Thanks.

Ge

**Comment by jforissier** [comment] 2017-05-10 06:44
Hi Ge,

What version of OP-TEE are you using? The secure storage implementation has changed quite a lot recently, with the introduction of better integrity checking via a hash tree. As a result, the files block1.0, block2.0 etc. are not used anymore.
So I would suggest you upgrade your version of OP-TEE to master or the latest release (2.4.0). If it is too difficult for some reason, then please at least make sure your code is based on an official release (2.3.0, 2.2.0 and so on) because code randomly taken from the master branch might be unstable sometimes.

**Comment by ggao-inven** [comment] 2017-05-10 19:12
Thanks for the answer. I upgrade my OS to 2.4.0. However, I found that the first call of TEE_CratePersistentObject already failed with 0xffff0006. It is a panic. It is a bad_parameters. However, I can't find why it is bad parameters. This function was working before in the older versions. Only the length could be bad parameters. But my object length is only 13 bytes. Any idea of this?

Thanks.

Ge

**Comment by ggao-inven** [comment] 2017-05-11 18:17
I found that I didn't update tee-supplicant and libteec. However, after I update the libteec and tee-supplicant both to 2.4.0. The first storage command give me a Panic 0x0 value. Any idea what might go wrong?

Thanks.

Ge

**Comment by ggao-inven** [comment] 2017-05-11 18:41
The panic value is 0xffff0006, bad parameters. I was using TEE_CreatePersistentObject. I was using 2.2.0 and it was working for this function call.


Thanks.

Ge

**Comment by jforissier** [comment] 2017-05-11 19:19
Hi Ge,

As much as I would like to help, I can't without seeing your code, and even then it may be difficult to figure out what is happening without instrumenting the code.
Add traces to the code (DMSG(""") for instance) and it will become clear what the problem is.

**Comment by ggao-inven** [comment] 2017-05-11 20:26
The code is really simple. It just directly call the createpersistentobject.
I was using 2.2.0 release of OPTEE. Now I upgrade OPTEE to 2.4.0 and libteec and tee-supplicant to 2.4.0 too. It gave me BAD_PARAMETERS issue. Then I upgrade Linux under Juno_box to "lsk-4.4-armlt-20170111". It is now gave me the error of 0xFFFF0008, which is ITEM_NOT_FOUND error.
Below is the code.
Thanks.

static char objectID[MAX_OBJECTID_LEN];
static TEE_Result inv_store_key(void)
{
	TEE_ObjectHandle obj;
	size_t objectIDLen;
	TEE_Result res;

	/* save activation code here */
	TEE_MemFill(objectID, 0, sizeof(objectID));
	TEE_MemMove(objectID, ac_file, sizeof(ac_file));
	objectIDLen = sizeof(objectID);
	EMSG("store ac here22=%d", objectIDLen);
        EMSG("REE store %x", TEE_STORAGE_PRIVATE);

	res = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, objectID, objectIDLen,
			TEE_DATA_FLAG_ACCESS_WRITE
			, NULL, cnf_ac,
			INV_FP_AC_LENGTH, &obj);

**Comment by ggao-inven** [comment] 2017-05-11 22:32
It might be the memory allocated to TA is too small. Is there anyway to increase that?
I am using a default user_ta_header_defines.h.
Here is the file:
#ifndef USER_TA_HEADER_DEFINES_H
#define USER_TA_HEADER_DEFINES_H

#define TA_UUID DNY_INV_UUID

#define TA_FLAGS                    (TA_FLAG_EXEC_DDR)
#define TA_STACK_SIZE               (20 * 1024 * 4)
#define TA_DATA_SIZE                (640 * 1024 * 6)

#define TA_CURRENT_TA_EXT_PROPERTIES \
    { "gp.ta.description", USER_TA_PROP_TYPE_STRING, \
        "inv TA" }, \
    { "gp.ta.version", USER_TA_PROP_TYPE_U32, &(const uint32_t){ 0x0010 } }

#endif /*USER_TA_HEADER_DEFINES_H*/

**Comment by ggao-inven** [comment] 2017-05-12 18:36
I finally make the 2.4.0 version works in my environment. The saving of the file seems OK now. However, I have other problems when I uses 2.4.0 I will ask in another thread.
Thanks

Ge

**Comment by jbech-optee-adm** [comment] 2017-10-06 13:59
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins

**Closed by jbech-optee-adm** 2017-10-06 13:59 UTC
