### ISSUE TITLE
REE FS tree in Linux FS

### ISSUE THREAD

**Issue by ppeiffer** [OP-TEE/optee_os#1572] opened 2017-05-31 12:50 UTC
Hi,
In the doc included in optee-os, I can read (file documentation/secure_storage.md) the persistent object are stored in Linux FS using a tree like /data/tee/<ta_uuid>/<obj_id>

But when looking on linux FS, I see this:
```
$ ls -l /data/tee
total 2768
-rw------- 1 root  root   16384 1970-01-01 00:00 0
-rw------- 1 root  root   16384 1970-01-01 00:00 1
-rw------- 1 root  root  503808 1970-01-01 00:04 2
-rw------- 1 root  root   16384 1970-01-01 00:04 3
-rw------- 1 root  root  557056 1970-01-01 00:04 4
-rw------- 1 root  root   16384 1970-01-01 00:04 5
-rw------- 1 root  root   16384 1970-01-01 00:03 6
-rw------- 1 root  root  479232 1970-01-01 00:04 7
-rw------- 1 root  root  479232 1970-01-01 00:03 8
-rw------- 1 root  root   16384 1970-01-01 00:03 9
-rw------- 1 root  root   16384 1970-01-01 00:04 b
-rw------- 1 root  root  495616 1970-01-01 00:03 c
-rw------- 1 root  root   16384 1970-01-01 00:04 dirf.db
drwxrwxr-x 2 shell shell   4096 1970-01-01 00:00 optee_armtz

```
I didn't check in the code, but what am I missing ?

P.

**Comment by vchong** [comment] 2017-05-31 13:04
Closing. Duplicate of #1571.

**Closed by vchong** 2017-05-31 13:04 UTC
