### ISSUE TITLE
Protecting UART3 from malicious Normal world (TZPC)

### ISSUE THREAD

**Issue by toddkuhreng** [OP-TEE/optee_os#1065] opened 2016-09-22 13:45 UTC
Hey,

I would like to make sure normal world cannot read or write to UART3 pins. 
Is it possible to achieve this using TZPC or any similar feature on Hikey board?
Any pointer is greatly appreciated. 

My use case is that secure world is sending out sensitive data using this UART3 ports
and malicious normal world should never able to access (read/write into) these pins (I don't want to share these  pins with NW at all). Please let me know.

Thanks a lot,

**Comment by jforissier** [comment] 2016-09-23 12:07
Hi @toddkuhreng,

I believe HiKey has a TZPC. Unfortunately, I am not aware of any public programming documentation for this IP. I will try to get more details from HiSilicon and keep you posted.

**Comment by toddkuhreng** [comment] 2016-09-26 09:55
Hi @jforissier ,

I am pretty much stuck with this part. It would be really great if you 
can get more details on this from HiSilicon. 

Meanwhile, is there any other way to reverse engineer this IP? 
If so, any pointers on where to start? 

Thank you so much

**Comment by jforissier** [comment] 2016-10-03 09:46
Hi @toddkuhreng ,

Here is some example code that HiSilicon allowed me to share publicly. I don't have the proper adapter to connect a serial console to HiKey's `uart3` (a.k.a. `LS-UART1` or `uart@f7113000` in [hi6220.dtsi](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/arch/arm64/boot/dts/hisilicon/hi6220.dtsi?id=refs/tags/v4.8#n306)). So, I could not test it rigorously. However, with this code applied, it seems I can still access `uart3` from OP-TEE but not from the Linux kernel. More precisely, when I tried sending text to `uart3` from OP-TEE it did not cause any exception, while the Linux kernel would dump error messages unless `uart3` is removed from the DT.

```C
#define TZPC_BASE          0xF8002000
#define TZPC_SIZE          0x878

#define SLAVE_PROTX_SET    0x834
#define set_sec_uart3      BIT(29)

register_phys_mem(MEM_AREA_IO_SEC, TZPC_BASE, TZPC_SIZE);

static TEE_Result tzpc_init(void)
{
	vaddr_t tzpc = (vaddr_t)phys_to_virt(TZPC_BASE, MEM_AREA_IO_SEC);

	/* Restrict UART3 access to secure mode */
	write32(set_sec_uart3, tzpc + SLAVE_PROTX_SET);
	return TEE_SUCCESS;
}

driver_init(tzpc_init);
```

Hope this helps!

**Comment by toddkuhreng** [comment] 2016-10-05 12:37
Hi @jforissier ,

Thank you so much for sharing this. I have a question about this sample code. Could you please help me to understand?

Following code basically will write  1 << 29 to a specific register of TZPC, right? 
What is this register's name and why '1 << 29'? 

` write32( (BIT(29) , tzpc + SLAVE_PROTX_SET);`

The thing is, I also want to make following GPIO port only accessible from secure world. 

`
#define GPIO2_BASE              0xF8013000  // 16-23 
`
How does this code change for achieving that?   Could you please help me with this too?  Thanks a ton

Thanks again,

**Comment by jforissier** [comment] 2016-10-05 14:38
Your understanding of the code is correct. Setting bit 29 of register `SLAVE_PROTX_SET` of the TZPC configures UART 3 as a secure device. What other name do you expect for the register? That's the name I was given.
For GPIO2 I don't know but I'll try to find out.

**Comment by toddkuhreng** [comment] 2016-10-05 15:36
Hi @jforissier, 

I just now tested securing UART3 device code, apparently it is not working for me. 

I added this file [/core/arch/arm/plat-hikey/tzpc_uart3.c](https://gist.github.com/toddkuhreng/78fd493cc9fc7993a0d108248ccf0568)


Also, updated the makefile with following:
```
CFG_NW_CONSOLE_UART ?= 0 
CFG_SW_CONSOLE_UART ?= 3
```

On minicom I see only the print message just before the write32 call as shown in the following picture: 

![tcpc](https://cloud.githubusercontent.com/assets/20192842/19119793/3236cf7e-8b21-11e6-97ae-d58067042632.png)

So it looks like system is stuck/hung on write32 call.  I don't see the print messages after write32 function call. Why is it not working for me? 

Thanks a lot,

**Comment by jforissier** [comment] 2016-10-05 17:13
Hi @toddkuhreng,

For this use case, I think you need to map the console memory as secure. Also you might want to configure the TZPC in console_init(), so that your console is secure from the start. Doing so is also a bit simpler because you can directly write the register using its physical address. Indeed the MMU is not enabled at this point.

So all you need should be:

```diff
diff --git a/core/arch/arm/plat-hikey/main.c b/core/arch/arm/plat-hikey/main.c
index 3ede9ad..375cf31 100644
--- a/core/arch/arm/plat-hikey/main.c
+++ b/core/arch/arm/plat-hikey/main.c
@@ -51,7 +51,11 @@ static const struct thread_handlers handlers = {
        .system_reset = pm_do_nothing,
 };
 
-register_phys_mem(MEM_AREA_IO_NSEC, CONSOLE_UART_BASE, PL011_REG_SIZE);
+register_phys_mem(MEM_AREA_IO_SEC, CONSOLE_UART_BASE, PL011_REG_SIZE);
+
+#define TZPC_BASE              0xF8002000
+#define SLAVE_PROTX_SET        0x834
+#define set_sec_uart3          BIT(29)
 
 const struct thread_handlers *generic_boot_get_handlers(void)
 {
@@ -69,7 +73,7 @@ static vaddr_t console_base(void)
 
        if (cpu_mmu_enabled()) {
                if (!va)
-                       va = phys_to_virt(CONSOLE_UART_BASE, MEM_AREA_IO_NSEC);
+                       va = phys_to_virt(CONSOLE_UART_BASE, MEM_AREA_IO_SEC);
                return (vaddr_t)va;
        }
        return CONSOLE_UART_BASE;
@@ -77,6 +81,7 @@ static vaddr_t console_base(void)
 
 void console_init(void)
 {
+       write32(set_sec_uart3, TZPC_BASE + SLAVE_PROTX_SET);
        pl011_init(console_base(), CONSOLE_UART_CLK_IN_HZ, CONSOLE_BAUDRATE);
 }
 
```

**Comment by toddkuhreng** [comment] 2016-10-05 20:27
Hi @jforissier,

Thank so much for the detailed explanation. 

I tried this code; however  the Hikey board keeps rebooting after trying to switch to normal world.  [Here is the UART3 debug logs](https://gist.github.com/toddkuhreng/5bf90c8d6b4e7337088ca599f2e1eda4). Any idea why is this happening? 

Thank a lot again.

**Comment by jforissier** [comment] 2016-10-05 20:40
Strange. If you remove only the `write32()`, does it work ?

**Comment by toddkuhreng** [comment] 2016-10-05 21:20
Hi @jforissier ,

I tried two things first I commented out `write32(set_sec_uart3, TZPC_BASE + SLAVE_PROTX_SET);`  and then it booted to normal world without any issues.  

Btw, I came across [this blog ](http://m.blog.csdn.net/article/details?id=51312871) where the author is talking about calling `tzpcdep_init(PERI_BASE)` which basically calls `write32(PERI_CLK3_TZPC_DEP, PERI_BASE + PERI_SC_PERIPH_CLKEN3);` Should I do that too ? 

Also, I tried to read back the TZPC register value using following code and the execution was stuck inside the do..while loop. Register value is printed as 0x0 before it entered the do..while loop. 
```

void console_init(void)
{
 IMSG("####################################Securing UART!!!!");
 write32(set_sec_uart3, TZPC_BASE + SLAVE_PROTX_SET);
  IMSG("############TZPC register value : value 0x%x\n",read32(TZPC_BASE + SLAVE_PROTX_SET));
  do {
           data = read32( TZPC_BASE + SLAVE_PROTX_SET );

     } while (!(data & set_sec_uart3));

pl011_init(console_base(), CONSOLE_UART_CLK_IN_HZ, CONSOLE_BAUDRATE);
}
```


Thanks again,

**Comment by jforissier** [comment] 2016-10-05 21:36
About `CLKEN3`, I don't know. Try it... It might help in case this clock is not enabled by default...
As for reading back `SLAVE_PROTX_SET` I would guess it won't work because it is write-only. A different register may be used to reset and yet another one to read the status.

**Comment by toddkuhreng** [comment] 2016-10-05 22:15
I tried setting `CLKEN3` too, the board still keeps on rebooting.  So `write32(set_sec_uart3, TZPC_BASE + SLAVE_PROTX_SET);` is causing the hikey board to [reboot](https://gist.github.com/toddkuhreng/5bf90c8d6b4e7337088ca599f2e1eda4). Anything else that I can try to figure the problem? Did setting this register worked for you?

Also, it would be a great help if you can share the details on what bit and what register should be modified to make GPIO2 secure.

Thank you,

**Comment by jforissier** [comment] 2016-10-05 22:23
Also, try removing any reference to uart3 in the DT.  It might be the cause of the reboots? (although I would rather expect some exception on access).

**Comment by jforissier** [comment] 2016-10-06 07:58
Seems to be works fine here.
As I said, I have my console connected to UART0, and everything (ARM-TF, GRUB, kernel) is configured to use UART0 except OP-TEE  which I build with `CFG_CONSOLE_UART=3`. I don't have a serial cable for UART3 so I can't confirm 100% if OP-TEE messages indeed go to UART3. But, with the code I posted above (https://github.com/OP-TEE/optee_os/issues/1065#issuecomment-251738274), the board boots properly, I don't see the OP-TEE logs, and the kernel crashes as expected when trying to access the secure UART: http://pastebin.com/LEexW3Dt

Then if I disable UART3 in the DT:
```diff
diff --git a/arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts b/arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts
index b6a06fb..528567d 100644
--- a/arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts
+++ b/arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts
@@ -63,7 +63,7 @@
                };
 
                uart3: uart@f7113000 {
-                       status = "ok";
+                       status = "disabled";
                };
 
                /*
```
...then everything looks fine (except for some login process spewing "can't open /dev/ttyAMA3: No such file or directory").

**Comment by toddkuhreng** [comment] 2016-10-06 18:19
Hi @jforissier ,

Thank you for the reply. What does making status disabled do actually? I am guessing it removes the peripheral from 'normal world' (not from secure world), is that correct?   

Also, [My hi6220-hikey.dts](https://gist.github.com/toddkuhreng/1c0bceba146ca42421eb4ef47f81d23c) file looks different from what you have shown. Could you please share your hi6220-hikey.dts file?  
[ And here is my changes](https://gist.github.com/toddkuhreng/a86e26a6e1a2c65dcc060975d8246f9e). With this code, Hikey board keeps on rebooting for me. Is it possible to share your fip.bin, just to make sure my Hikey board is okay and it is something I am missing in the code? Btw, I am running Android on normal world; I hope that is not creating any problems.

Thanks again,

**Comment by jforissier** [comment] 2016-10-06 18:46
Hi @toddkuhreng,

You're right, status disabled in DT means normal world will not access the device.
I'm using kernel 4.8.0 for this test. My master project is https://github.com/jforissier/hikey_optee (you'll get a 4.5.0 kernel with this Git). It is a very simple busybox-based environment with everything I need for development and testing.
I don't see any memory reservation for OP-TEE in your DT, are you sure you have one ?

**Comment by toddkuhreng** [comment] 2016-10-06 21:05
I think, I shared wrong DT file. Here is what I am doing. 

1) I checked out the [optee+aosp repo from here](https://github.com/linaro-swg/optee_android_manifest) and build the normal world image (Android). 

2) Then I checked out  [OP-TEE (Hikey)](https://github.com/OP-TEE/optee_os/blob/master/README.md#55-hikey) using following command to build "`fip.bin"` using following command:

`repo init -u https://github.com/OP-TEE/manifest.git -m hikey.xml -b master`

------------------------------
[`hi6220-hikey.dts`](https://github.com/linaro-swg/linux/blob/master/arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts) file inside `Linux kernel` that comes with `Hikey master branch` doesn't contain memory reservations for OP-TEE. As I am using it to just create `fip.bin`, that is fine, correct? 
Or should i use linux kernel `aosp-optee-4.4` for creating` fip.bin` too? 

Also,  [hi6220-hikey.dts](https://gist.github.com/toddkuhreng/c01cc6d1f5b6ebe53f1bd0ea9b70daaa) file inside [OPTEE+AOSP](https://github.com/linaro-swg/optee_android_manifest) has memory reservations for OP-TEE.

Anyways, I am now trying to check out your master project now. It is failing to checkout sub modules grub and linux. I will use your forked repo of grub. Btw, what are you running on normal world, is it Android?

Thank you,

**Comment by jforissier** [comment] 2016-10-06 21:20
About the memory reservation, my mistake -- it is done by UEFI for HiKey.
I'll check the submodule references in hikey_optee, something may be wrong. In the meantime, you can check out https://github.com/linaro-swg/linux.git branch optee. For grub, get the latest from upstream, it should work. Change the UART in the main Makefile if you're using UART3 because everything goes to UART0 by default.

The DT is used only by the kernel not by anything in fip.bin so just make sure it is correct for you kernel, and as I said the memory reservation is done by UEFI.

**Comment by jforissier** [comment] 2016-10-06 21:35
BTW using `repo` should be fine. I would suspect your kernel, how do you get it/build it? Try building the repo project, or my project, entirely, without changing anything, and run xtest. When that works, apply the secure uart modification and test again.

**Comment by jbech-optee-adm** [comment] 2016-11-03 09:20
We're closing this issue since the question has been answered and there hasn't been any activity for more than a month. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Closed by jbech-optee-adm** 2016-11-03 09:20 UTC

**Comment by toddkuhreng** [comment] 2017-01-26 14:53
Hi @jforissier ,


Sorry for the late reply. I am testing protecting UART3 using [your repo](https://github.com/jforissier/hikey_optee/blob/master/Makefile) as you described. I have shell access to hikey board through UART0. How do I see the logs from secure world on UART3?  

I tried by adding following to the Makefile. Still I don't see anything from secure world on UART3.
```

CFG_CONSOLE_UART ?= 0
CFG_SW_CONSOLE_UART ?= 3

optee-os-flags += CFG_CONSOLE_UART=$(CFG_CONSOLE_UART)
optee-os-flags += CFG_SW_CONSOLE_UART=$(CFG_SW_CONSOLE_UART)
```

What change should I make in Makefile to see secure world logs on UART3 too? Could you help with this?

**Comment by jforissier** [comment] 2017-01-26 14:57
Hi @toddkuhreng ,

Just change this:
```
CFG_CONSOLE_UART ?= 0
optee-os-flags += CFG_CONSOLE_UART=$(CFG_CONSOLE_UART)
```
...to this:
```
CFG_CONSOLE_UART ?= 3
optee-os-flags += CFG_CONSOLE_UART=$(CFG_CONSOLE_UART)
```
...or simply build using "make CFG_CONSOLE_UART=3".

There is no such config variable `CFG_SW_CONSOLE_UART` in optee_os. So the change you did is essentially a no-op ;)

**Comment by jbech-linaro** [comment] 2017-01-26 15:09
In build.git there is [CFG_SW_CONSOLE_UART](https://github.com/OP-TEE/build/search?utf8=%E2%9C%93&q=CFG_SW_CONSOLE_UART), but since he says he is using your stuff .. you're probably right :)

**Comment by toddkuhreng** [comment] 2017-01-27 15:01
Hi @jforissier 

Yes, you are right.  so I now able to see TEE core messages on UART3 :)  But I don't see any debug messages from my TA app. 


I have lots of DEBUG messages on my TA like the following:

```
TEE_Result TA_CreateEntryPoint(void)
{
  DMSG("TA Create entry point has been called");
  return TEE_SUCCESS;
}

```

I can execute my TA apps successfully, but I don't see these debug messages from TA on UART3. Why is that? Is this about any configuration flag in Makefile? 


```

INFO:    TEE-CORE: Initialized
DEBUG:   [0x0] TEE-CORE:init_primary_helper:628: Primary CPU switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 1: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 2: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 3: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 4: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 5: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 6: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 7: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot

```


Also,, if you are using official hikey build, yes,  there is  CFG_SW_CONSOLE_UART flag :)

**Comment by jforissier** [comment] 2017-01-27 15:06
> Hi @jforissier 
> 
> Yes, you are right.  so I now able to see TEE core messages on UART3 :)  But I don't see any debug messages from my TA app. 
> 
> 
> I have lots of DEBUG messages on my TA like the following:
> 
> ```
> TEE_Result TA_CreateEntryPoint(void)
> {
>   DMSG("TA Create entry point has been called");
>   return TEE_SUCCESS;
> }
> 
> ```
> 
> I can execute my TA apps successfully, but I don't see these debug messages from TA on UART3. Why is that? Is this about any configuration flag in Makefile? 

You need to set `CFG_TEE_TA_LOG_LEVEL=3` when building your TA. There is one log level for TEE core, another one for user libraries / TAs.

[...]
> 
> Also,, if you are using official hikey build, yes,  there is  CFG_SW_CONSOLE_UART flag :) 
> 

Yes, I know ;)

**Comment by toddkuhreng** [comment] 2017-04-15 12:35
Hi @jforissier ,

Sorry to bother you again about this issue I am facing. I tried many combination 
to get the print messages in TEE core to get working and still no luck!
Following is that I have in my config, and make Makefiles. I am kind of lost here. 
Can you please help? 

Problem I am facing is that I can't find  any `Debug messages from TA and STA` on UART3.
All I see in UART3 is following:

```
DEBUG:   [0x0] TEE-CORE:spi_init:150: enable SPI clock
DEBUG:   [0x0] TEE-CORE:spi_init:158: PERI_SC_PERIPH_CLKEN3: 0x0
DEBUG:   [0x0] TEE-CORE:spi_init:161: PERI_SC_PERIPH_CLKSTAT3: 0x2403c1
DEBUG:   [0x0] TEE-CORE:spi_init:172: configure gpio6_{0,1,3} as SPI
DEBUG:   [0x0] TEE-CORE:spi_init:173: configure gpio6_2 as GPIO
DEBUG:   [0x0] TEE-CORE:spi_init:179: configure gpio6_{0:3} as nopull
INFO:    TEE-CORE: Initialized
DEBUG:   [0x0] TEE-CORE:init_primary_helper:628: DMSG Primary CPU switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 1: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 2: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 3: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 4: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 5: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 6: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot
DEBUG:   TEE-CORE:generic_boot_cpu_on_handler:662: cpu 7: a0 0x3f000f24
DEBUG:   TEE-CORE:init_secondary_helper:647: Secondary CPU Switching to normal world boot


```

Following is what I have in makefiles and config files: 

Inside my build/hikey.mk file I have following:
```

CFG_NW_CONSOLE_UART ?= 0
CFG_SW_CONSOLE_UART ?= 3
OPTEE_OS_COMMON_FLAGS += PLATFORM=hikey
CFG_CONSOLE_UART=$(CFG_SW_CONSOLE_UART)
OPTEE_OS_CLEAN_COMMON_FLAGS += PLATFORM=hikey

CFG_TEE_CORE_LOG_LEVEL ?= 3 # 0=none 1=err 2=info 3=debug 4=flow
OPTEE_OS_COMMON_FLAGS += CFG_TEE_CORE_LOG_LEVEL=$(CFG_TEE_CORE_LOG_LEVEL)
OPTEE_OS_COMMON_FLAGS += DEBUG=1
OPTEE_OS_COMMON_FLAGS += CFG_WITH_PAGER=n
OPTEE_OS_COMMON_FLAGS += CFG_TEE_TA_LOG_LEVEL=3

```

inside hello_world/ta/Makefile I have following:

```
CFG_TEE_TA_LOG_LEVEL ?= 3
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)
```

Inside ./optee_os/mk/config.mk I have following: 
```

CFG_TEE_CORE_DEBUG ?= y
CFG_TEE_CORE_LOG_LEVEL ?= 3
CFG_TEE_TA_LOG_LEVEL ?= 3
CFG_TEE_CORE_TA_TRACE ?= y

```

Inside STA I have following:

```
static TEE_Result test_trace(uint32_t param_types __unused,
                        TEE_Param params[TEE_NUM_PARAMS] __unused)
{

        IMSG("static TA \"%s\" says \"Hello world !\"", TA_NAME);
        return TEE_SUCCESS;
}
```

Inside TA I have following:

```
TEE_Result TA_CreateEntryPoint(void)
{
  DMSG("TA Create entry point has been called");
  return TEE_SUCCESS;
}


```
And following is how I am building the whole image: 
`make  CFG_TEE_TA_LOG_LEVEL=3 CFG_TEE_CORE_LOG_LEVEL=3`

What am I missing here? Any help?

**Comment by rounaka** [comment] 2019-07-17 19:38
> Hi @toddkuhreng ,
> 
> Here is some example code that HiSilicon allowed me to share publicly. I don't have the proper adapter to connect a serial console to HiKey's `uart3` (a.k.a. `LS-UART1` or `uart@f7113000` in [hi6220.dtsi](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/arch/arm64/boot/dts/hisilicon/hi6220.dtsi?id=refs/tags/v4.8#n306)). So, I could not test it rigorously. However, with this code applied, it seems I can still access `uart3` from OP-TEE but not from the Linux kernel. More precisely, when I tried sending text to `uart3` from OP-TEE it did not cause any exception, while the Linux kernel would dump error messages unless `uart3` is removed from the DT.
> 
> ```c
> #define TZPC_BASE          0xF8002000
> #define TZPC_SIZE          0x878
> 
> #define SLAVE_PROTX_SET    0x834
> #define set_sec_uart3      BIT(29)
> 
> register_phys_mem(MEM_AREA_IO_SEC, TZPC_BASE, TZPC_SIZE);
> 
> static TEE_Result tzpc_init(void)
> {
>     vaddr_t tzpc = (vaddr_t)phys_to_virt(TZPC_BASE, MEM_AREA_IO_SEC);
> 
>     /* Restrict UART3 access to secure mode */
>     write32(set_sec_uart3, tzpc + SLAVE_PROTX_SET);
>     return TEE_SUCCESS;
> }
> 
> driver_init(tzpc_init);
> ```
> 
> Hope this helps!

@jforissier Do you know how to achieve the same in Hikey960 board ? If not, can you tell me whom I should ask ?

**Comment by vchong** [comment] 2019-07-18 08:33
@rounaka

**NOTE**: It's summer time and many people in the core team is on vacation, so expect delayed answers to both questions as well as feedback in pull requests!

Afaik we've not received from Hisilicon similar code for Hikey960 board, and these kind of code are usually not shared due to security concerns. @prime-zeng any comments?

**Comment by rounaka** [comment] 2019-07-18 18:01
> @rounaka
> 
> **NOTE**: It's summer time and many people in the core team is on vacation, so expect delayed answers to both questions as well as feedback in pull requests!
> 
> Afaik we've not received from Hisilicon similar code for Hikey960 board, and these kind of code are usually not shared due to security concerns. @prime-zeng any comments?

@vchong, since they shared the code for Hikey, I thought they wouldn't mind sharing it for Hikey960 as well. If I knew how to contact them directly, I would. I can also ask my advisor at university to write to them if that would help.
