### ISSUE TITLE
IBART to run PKCS#11 tests?

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#4306] opened 2021-01-07 09:40 UTC
Quite a lot of work has been done on PKCS#11 support already, and changes keep coming in, so I'm thinking it would be a good idea to run the PKCS#11 tests during CI (IBART). HiKey or QEMU, it doesn't matter much I suppose. It can be done quite easily by adding:
```
CFG_IN_TREE_EARLY_TAS=pkcs11/fd02c9da-306c-48c7-a49c-bbd827ae86ee CFG_PKCS11_TA=y
```
...to the build command (the first option is used by `optee_os`, the second one by `optee_test`). I tried on QEMU, it works fine.

What do you think?

**Comment by jbech-linaro** [comment] 2021-01-07 09:52
> What do you think?

Absolutely agree. I let others chime in and if the general consensus is "yes", then I'll enable it later today.

**Comment by ruchi393** [comment] 2021-01-07 09:54
> > What do you think?
> 
> Absolutely agree. I let others chime in and if the general consensus is "yes", then I'll enable it later today.

I am in agreement too. We should go ahead and enable it.

**Comment by Emantor** [comment] 2021-01-07 09:55
Definitely agree.

**Comment by jenswi-linaro** [comment] 2021-01-07 09:57
Sound good.

**Comment by jbech-linaro** [comment] 2021-01-07 10:07
Ok, that was quick, I read this as a "yes", so I've now enabled it (my "Fixes" comment even closed this).

**Closed** 2021-01-07 10:06 UTC

**Comment by jbech-linaro** [comment] 2021-01-07 10:10
Btw, I don't know how much PKCS#11 changes build-time and testing-time. There is some buffer, but in case it time out, then I might need to increase the timeout a bit also. We'll see ...

**Comment by jforissier** [comment] 2021-01-07 10:22
> Btw, I don't know how much PKCS#11 changes build-time 

Not much I think, the TA is built in any case (even when not linked into the TEE as an early TA), and there is only one more C file in optee_test.

> and testing-time.

Almost negligible (QEMU):
```
$ time xtest -t pkcs11 >/dev/null
real    0m 2.25s
user    0m 0.14s
sys     0m 1.93s
```

**Comment by etienne-lms** [comment] 2021-01-07 10:42
Nice.
In the future they'll be long lasting test as generating big RSA keys, etc...
We'll have to use xtest test `level` to keep level 0 tests quite fast.

**Comment by jforissier** [comment] 2021-01-07 12:29
Of course, Murphy will catch you every time... :cry: The test fails on HiKey with a decompression error as the early TA is loaded... See th [IBART log](https://optee.mooo.com:5000/logs/OP-TEE/optee_os/4307/551010162/2b543255c72c99c114758249d10e35927705b88d):
```
17779: E/TC:? 0 read_compressed:190 Decompression error (-4)
```
-4 is zlib error `Z_MEM_ERROR` so it looks like `CFG_CORE_HEAP_SIZE` is too small. Either we should try to increase it, or run PKCS#11 on QEMU only.

**Comment by jbech-linaro** [comment] 2021-01-07 12:36
> Either we should try to increase it, or run PKCS#11 on QEMU only.

I can/will disable it on Hikey temporarily, but probably better to fix the core issue where it's seen (i.e., increase the heap size).

**Comment by jenswi-linaro** [comment] 2021-01-08 07:53
Why do we need to load the PKCS#11 TA as an early TA?

**Comment by jforissier** [comment] 2021-01-08 08:08
> Why do we need to load the PKCS#11 TA as an early TA?

We don't have to, it is just easier than modifying the build scripts to install it in the proper location in the root FS ;-)
I suppose the optee_os_ext Buildroot package should take care of it...?

**Comment by jbech-linaro** [comment] 2021-01-08 08:39
> > Why do we need to load the PKCS#11 TA as an early TA?
> 
> We don't have to, it is just easier than modifying the build scripts to install it in the proper location in the root FS ;-)
> I suppose the optee_os_ext Buildroot package should take care of it...?

A nice side effect of this is that we actually have something running as early TA in our regression testing as well. I.e., the early TA stuff also will be tested now (build, deploy and run the code).

**Comment by jenswi-linaro** [comment] 2021-01-08 08:45
Another side effects seems to be to run out of heap though. The PKCS#11 TA is expected to continue to grow for a while yet so we may have a moving target here.

**Comment by jbech-linaro** [comment] 2021-01-08 08:54
> Another side effects seems to be to run out of heap though.

Correct and that makes me wonder what is the sweet spot for the configured heap size? I guess that is hard to answer, since it all depends on how much you actually enable. But if possible, it would probably make sense to configure it so at least the biggest TA can run without having to change it "manually". But I do see the challenge in coming up with a sane configuration for this.

Speaking about that, weren't you doing something related to heap usage. I.e., that is should be more predicable already from compile time? Or is just something that I've gotten wrong or was is stack usage? Only for user space TAs?

**Comment by etienne-lms** [comment] 2021-01-08 09:32
https://github.com/OP-TEE/build/pull/446 proposes a change to install PKCS11 TA in `/lib/optee_armtz/` from OP-TEE build.

**Comment by jenswi-linaro** [comment] 2021-01-08 09:52
https://projects.linaro.org/browse/LOC-365 will make the pager use less heap, almost on par with a configuration without paging.
It's those large memory allocations for tags that will be avoided. It means that very large TAs will not be a problem with the heap any longer.
