### ISSUE TITLE
Booting with Sabrelite board

### ISSUE THREAD

**Issue by wert91** [OP-TEE/optee_os#1284] opened 2017-01-11 11:38 UTC
Hi I'm trying to boot the optee OS on imx6q sabrelite board. I tried with the way suggested in issue #960 
Everything works fine except that the Linux kernel won't boot up when using SMC instruction. So the board is currently running optee and Linux on only one core.

```c
static int imx_boot_secondary(unsigned int cpu, struct task_struct *idle)
{
#if 0
    imx_set_cpu_jump(cpu, v7_secondary_startup);
    imx_enable_cpu(cpu, true);
#endif
#if 1
    struct arm_smccc_res  res;
    arm_smccc_smc(OPTEE_SMC_BOOT_SECONDARY,
        cpu, virt_to_phys(secondary_startup),
        0, 0, 0, 0, 0, &res);
#endif
return 0;
}
```

The kernel won't operate normally when the arm_smccc_smc code is inserted. I tracked the function and found out that this assembly code is causing the problem

```asm
UNWIND( .fnstart)
        mov r12, sp
        push    {r4-r7}
    UNWIND( .save   {r4-r7})
        ldm r12, {r4-r7}
        \instr
        pop {r4-r7}
        ldr r12, [sp, #(4 * 4)]
        stm r12, {r0-r3}
        bx  lr  
    UNWIND( .fnend)
```

The \instr is __smc and its definition is like this.

```c
#define __SMC(imm4) __inst_arm_thumb32(                 \
    0xE1600070 | (((imm4) & 0xF) << 0),             \
    0xF7F08000 | (((imm4) & 0xF) << 16)             \
)
```

How can I solve this issue and boot the remaining three cores? Currently I'm using kernel 3.14.28 and ported linux kernel drivers for optee. Thanks in advance.

**Comment by jforissier** [comment] 2017-01-11 12:58
Hi @wert91,

Are you able to run OP-TEE successfully on one core? (i.e., run `xtest`).
What 'problem' is caused by `arm_smccc_smc()`? Exception, hang...?

**Comment by wert91** [comment] 2017-01-12 08:51
It seems that the files are not loaded properly. xtest isn't working. I tried modprobe optee_armtz but it's not working. I think there's some problem with the drivers. Which version should I use for the kernel drivers out of these?? [](https://patchwork.kernel.org/project/linux-arm-kernel/list/?submitter=129291)

By the way if I use arm_smccc_smc() the device freezes after this message. 

> TEE-CORE:init_primary_helper:610: Primary CPU switching to normal world boot

It's very odd because the board does nothing related to Linux OS before that function. I think the board should output some messages related to setting arguments before executing arm_smccc_smc but it doesn't. However if I change the part __SMC() to do nothing, then the board starts up but fails to boot up other cores.
Thanks in advance.

**Comment by jbech-linaro** [comment] 2017-01-12 11:51
> I tried modprobe optee_armtz but it's not working. 

You should not to modprobe that, if you're running the driver we're using it would be built into the kernel itself.

>I think there's some problem with the drivers. Which version should I use for the kernel drivers out of these?? https://patchwork.kernel.org/project/linux-arm-kernel/list/?submitter=129291

v13 [here](https://patchwork.kernel.org/project/linux-arm-kernel/list/?submitter=129291) is the latest sent to the mailinglist and that is basically what we have on our kernel branch that we're using. The major difference is that you will see a few more device tree related commits for various devices. You'll find that kernel branch here (branch name: `optee`): https://github.com/linaro-swg/linux

**Comment by wert91** [comment] 2017-01-20 13:42
Hello, @jbech-linaro 
As I thought the kernel I used was outdated, so I upgraded to Linux 4.9.0 and only edited the part in arch/arm/mach-imx/platsmp.c to be the form I wrote at the first comment
```
static int imx_boot_secondary(unsigned int cpu, struct task_struct *idle)
{
#if 0
    imx_set_cpu_jump(cpu, v7_secondary_startup);
    imx_enable_cpu(cpu, true);
#endif
#if 1
    struct arm_smccc_res  res;
    arm_smccc_smc(OPTEE_SMC_BOOT_SECONDARY,
        cpu, virt_to_phys(secondary_startup),
        0, 0, 0, 0, 0, &res);
#endif
return 0;
}
```
and tried the way suggested in [https://github.com/OP-TEE/optee_os/pull/936#issuecomment-244699959](url)

and the log for this procedure was like this:

```
## Booting kernel from Legacy Image at 20000000 ...
   Image Name:
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    333972 Bytes = 326.1 KiB
   Load Address: 4dffffe4
   Entry Point:  4e000000
hab fuse not enabled
kernel_len 000518d4
ivt_offset 00052000
csf_addr 20052020
   Verifying Checksum ... OK
## Flattened Device Tree blob at 18000000
   Booting using the fdt blob at 0x18000000
EHCI failed to shut down host controller.
   Loading Kernel Image ... OK
   Using Device Tree in place at 18000000, end 1800c985

Starting kernel ...

DEBUG:   TEE-CORE:add_phys_mem:257: CFG_TEE_RAM_START 1 0x4e000000 size 0x00100000
DEBUG:   TEE-CORE:add_phys_mem:257: CFG_TA_RAM_START 3 0x4e100000 size 0x01e00000
DEBUG:   TEE-CORE:add_phys_mem:257: CFG_SHMEM_START 4 0x4ff00000 size 0x00100000
DEBUG:   TEE-CORE:add_phys_mem:257: CONSOLE_UART_BASE 7 0x02100000 size 0x00200000
DEBUG:   TEE-CORE:add_phys_mem:257: GIC_BASE 8 0x00a00000 size 0x00100000
DEBUG:   TEE-CORE:add_phys_mem:257: PL310_BASE 8 0x00a00000 size 0x00200000
DEBUG:   TEE-CORE:add_phys_mem:269: Physical mem map overlaps 0xa00000
DEBUG:   TEE-CORE:add_va_space:294: type 9 size 0x00a00000
DEBUG:   TEE-CORE:init_mem_map:439: type va 1 0x4e000000..0x4e0fffff pa 0x4e000000..0x4e0fffff size 0x100000
DEBUG:   TEE-CORE:init_mem_map:439: type va 3 0x4e100000..0x4fefffff pa 0x4e100000..0x4fefffff size 0x1e00000
DEBUG:   TEE-CORE:init_mem_map:439: type va 4 0x4ff00000..0x4fffffff pa 0x4ff00000..0x4fffffff size 0x100000
DEBUG:   TEE-CORE:init_mem_map:439: type va 7 0x50000000..0x501fffff pa 0x02100000..0x022fffff size 0x200000
DEBUG:   TEE-CORE:init_mem_map:439: type va 8 0x50200000..0x503fffff pa 0x00a00000..0x00bfffff size 0x200000
DEBUG:   TEE-CORE:init_mem_map:439: type va 9 0x50400000..0x50dfffff pa 0x00000000..0x009fffff size 0xa00000
INFO:    TEE-CORE: Initializing (2.2.0-162-g0299f82-dev #3 Fri Jan 20 07:21:17 UTC 2017 arm)
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_tmp[0] with top at 0x4e07a5f8
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x4e07a5fc
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_tmp[1] with top at 0x4e07aaf8
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x4e07aafc
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_tmp[2] with top at 0x4e07aff8
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x4e07affc
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_tmp[3] with top at 0x4e07b4f8
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x4e07b4fc
DEBUG:   [0x0] TEE-CORE:init_canaries:171: #Stack canaries for stack_abt[0] with top at 0x4e07bd38
DEBUG:   [0x0] TEE-CORE:init_canaries:171: watch *0x4e07bd3c
DEBUG:   [0x0] TEE-CORE:init_canaries:171: #Stack canaries for stack_abt[1] with top at 0x4e07c578
DEBUG:   [0x0] TEE-CORE:init_canaries:171: watch *0x4e07c57c
DEBUG:   [0x0] TEE-CORE:init_canaries:171: #Stack canaries for stack_abt[2] with top at 0x4e07cdb8
DEBUG:   [0x0] TEE-CORE:init_canaries:171: watch *0x4e07cdbc
DEBUG:   [0x0] TEE-CORE:init_canaries:171: #Stack canaries for stack_abt[3] with top at 0x4e07d5f8
DEBUG:   [0x0] TEE-CORE:init_canaries:171: watch *0x4e07d5fc
DEBUG:   [0x0] TEE-CORE:init_canaries:173: #Stack canaries for stack_thread[0] with top at 0x4e07f638
DEBUG:   [0x0] TEE-CORE:init_canaries:173: watch *0x4e07f63c
DEBUG:   [0x0] TEE-CORE:init_canaries:173: #Stack canaries for stack_thread[1] with top at 0x4e081678
DEBUG:   [0x0] TEE-CORE:init_canaries:173: watch *0x4e08167c
INFO:    TEE-CORE: OP-TEE Device Tree node already exists!
INFO:    TEE-CORE: Initialized
DEBUG:   [0x0] TEE-CORE:init_primary_helper:628: Primary CPU switching to normal world boot
```

I think the part in imx_boot_secondary which calls SMC is causing the problem. I'm currently not available with the JTAG debugger, so I'm having trouble finding the reason for the failure. Is the way suggested in the comment above still feasible? Or if that way can't be used what should I do to make optee run on imx6q-sabre lite?

Thanks in advance.

**Comment by MrVan** [comment] 2017-01-22 02:26
@wert91 I'll have a test on i.mx6q-sabresd and write a guide for that. There maybe no much difference between sabrelite and sabresd.

**Comment by wert91** [comment] 2017-01-23 04:34
@MrVan Thanks for your help!

**Comment by jeffy1009** [comment] 2017-01-23 14:35
Hello, @MrVan @jforissier @jbech-linaro 

Thank you for the help!

Me and @wert91 is trying to get our board to boot.
We have our custom 3.14 kernel, and we applied 2.0.0 driver patch backported for the 3.18 ([link](https://github.com/OP-TEE/optee_linuxdriver)) and also [this](https://github.com/OP-TEE/optee_os/pull/936#issuecomment-244699959) patch for SMP support.

It didn't work. There were no progress after `Primary CPU switching to normal world boot` message, even though we think that somethings going on in linux kernel but no kernel logs coming out.

So we tried to skip `imx_boot_secondary` function. Then we could see the linux kernel boot successfully, but optee driver initialization was failed.

Kernel log prints WARN_ON message from `pfn_valid`  in `__arm_ioremap_pfn_caller` function in `ioremap.c`.
The `pfn` value seems to be coming from the result of `arm_smccc_smc` call.

stack trace is: 
```
__arm_ioremap_pfn_caller
__arm_ioremap_caller
ioremap_cache
optee_config_shm_ioremap
optee_probe
...
```

Do you have some hint of what the problem might be?

**Comment by jenswi-linaro** [comment] 2017-01-23 15:24
Perhaps the carved out shared memory region is still in use by the kernel and used for something important.

**Comment by jeffy1009** [comment] 2017-01-24 14:45
Turns out that our board is not exactly the sabre lite board.. it is similar but has 2GB RAM (instead of 1GB).

RAM is mapped to 0x10000000 ~ 0x90000000 and OP-TEE requests ioremap for shared memory at 0x4ff01000 ~ 0x50000000 and fails.

I tried changing DRAM0_SIZE in `core/arch/arm/plat-imx/platform_config.h` from 0x40000000 to 0x80000000, and CFG_DDR_TEETZ_RESERVED_START from 0x4E000000 to 0x8E000000.

Now OP-TEE requests ioremap at 0x8ff01000 ~ 0x90000000, but still RAM is mapped to 0x10000000 ~ 0x90000000, so cannot succeed.

I've also tried setting DRAM0_SIZE to 0x7E000000 without success.

**Comment by jeffy1009** [comment] 2017-01-25 04:46
I see that DRAM memory need to be carved out in u-boot.
Something similar to [this](https://github.com/MrVan/u-boot/commit/934d1f0517a13ca406fac7682d097c05c1b3ca0d)
should be done to sabre lite board.
Also we were not using u-boot, so we need to figure out how to do it in our environment.

**Comment by MrVan** [comment] 2017-01-25 05:33
@jeffy1009  The reason `gd->ram_size = imx_ddr_size() - CONFIG_TEE_RAM_SIZE;`  is that uboot will be relocated to the high memory which conflicts with the memory that optee runs in. Also uboot will change the memory node in dtb according to `gd->ram_size` to avoid Linux overwritting the optee memory.

**Comment by MrVan** [comment] 2017-01-25 07:07
@jeffy1009  I have wrote a guide on how to enable OP-TEE on i.MX6Q-SDB board, [optee-imx6q-sabresd](http://mrvan.github.io/optee-imx6q-sabresd). I think there should be not much difference between your board and im6qsabresd board. Hope the guide could help you fix your issues.

**Comment by jbech-linaro** [comment] 2017-01-25 13:51
> @MrVan 
> @jeffy1009 I have wrote a guide on how to enable OP-TEE on i.MX6Q-SDB board

Based on the discussion two weeks ago regarding docs. Would you mind me picking up those instructions and put them in our build.git? So far all there based on repo builds with the Makefiles for each target, but my impression is that you keep the instructions up to date and therefore I wouldn't mind moving your guide over there. What do you say?

**Comment by jeffy1009** [comment] 2017-01-27 14:31
@MrVan  Thanks for the guide.
We have succeeded in bringing up the tee driver by fixing uboot similarly to [this](https://github.com/MrVan/u-boot/commit/934d1f0517a13ca406fac7682d097c05c1b3ca0d)

However, we still need to boot multi cores. We have tested 3.14.x kernel and 4.1.x kernel. With 4.1.x kernel, multi-core booting works, but we'd like to use 3.14.x since we have configured the kernel for our custom sabrelite-like board.

In 3.14.x kernel, I found that `generic_boot_core_release` is executed by the primary core and set the spin_table for the secondary core. But strangely, secondary cores cannot see the value is changed and keep spinning in `generic_boot_core_hpen`. (In 4.1.x kernel, it can see the value change alright)

I don't know if its some strange cache effect, but can cache behavior in OP-TEE effected by the linux kernel??

Also, I've run xtest with both 3.14.x and 4.1.x kernel, but half of the test fails. Does the original imx boards pass all the tests? I see that QEMU pass all the tests.

**Comment by jeffy1009** [comment] 2017-01-30 17:30
For 3.14.x kernel, I've tried using cache_maintenance_l1, l2 CLEAR and INVALIDATE functions and I could see that the secondary cores see the value changed by the primary core.

However, if I use those functions, the secondary cores "fail to come online", even for 4.1.x kernel!

Looking at the commit history, I've also tried to not use `hpen` but instead reset the secondary cores (that is, before cee96842b59e9a83accb8d03448c5f779fe35ed2 commit is introduced) in `generic_boot_core_release`, and setting `CFG_BOOT_SYNC_CPU=n` 

I see that I need to use `phys_to_virt` for `SRC_BASE` since mmu is enabled at that point. But when I try to set `CFG_TEE_LOAD_ADDR` [like this](https://github.com/OP-TEE/optee_os/blob/93091fda396dc4717c75cd06e7ac335363b56abf/core/arch/arm/plat-imx/main.c#L157), [`src_base`](https://github.com/OP-TEE/optee_os/blob/93091fda396dc4717c75cd06e7ac335363b56abf/core/arch/arm/plat-imx/main.c#L125) cannot find the mapping (`MEM_AREA_IO_SEC`) and returns address 0, causing tee-core panic.

I'd appreciate if someone point out if I'm missing some point. Thank you

**Comment by MrVan** [comment] 2017-02-04 02:15
@jeffy1009 I did not use 3.14, I use 4.1 now.  Also I switched to use PSCI, then CFG_BOOT_SYNC_CPU is not needed. 

If `src_base` can not find the mapping, you need to dump the mmu table using JTAG to see whether SRC address space is mapped or not. `register_phys_mem(MEM_AREA_IO_SEC, SRC_BASE, CORE_MMU_DEVICE_SIZE);` will let OP-TEE core to create the mapping. Werid that `src_base` returns 0.

**Comment by jeffy1009** [comment] 2017-02-06 15:52
@MrVan I'm trying the PSCI patches. (both OP-TEE and the imx-linux)

shouldn't `imx_boot_secondary` changed to do std_smc call?

currently my board does not enter `smc_std_handler`

**Comment by jeffy1009** [comment] 2017-02-07 04:02
@MrVan Hello, I've changed `OPTEE_SMC_BOOT_SECONDARY` in `imx_boot_secondary` as follows
```
#define OPTEE_SMC_BOOT_SECONDARY  \                                
        ARM_SMCCC_CALL_VAL(ARM_SMCCC_FAST_CALL, ARM_SMCCC_SMC_32, \
                           ARM_SMCCC_OWNER_STANDARD, 3)            
```

and also as `ns_entry` is passed in `a3`, I changed OP-TEE code to pass `a3` to `psci_cpu_on` as `entry` paramter.

I think it should work, but in `3.14.x` kernel, strange cache effect occurs as I have mentioned above.
`ns_entry_addr[core_idx]` set by CPU0 is visible by CPU1 but not visible by CPU2 and 3.

The reason we were using the old kernel was because we already adapted our project to that version of the kernel, but if it is hard to get support with this version, I guess we better move to the newer kernel.

**Comment by MrVan** [comment] 2017-02-07 06:30
@jeffy1009 If using psci, `imx_boot_secondary` will not be used. `arch/arm/kernel/psci*.c` will be used for smp functions. I am not sure if you are using the latest upstream optee os code or legacy releases. Have you tried disable L2Cahce? Disable L2 in kernel and disable CFG_PL310 and CFG_PL310_LOCK in OPTEE.

**Comment by jeffy1009** [comment] 2017-02-15 06:39
@MrVan  Hello, I'm using 192cd5688293ff32779ed6d5e5861169ffe0b109 commit of OP-TEE, and we've applied all the latest tee related commits from [here](https://github.com/MrVan/linux/commits/imx_4.1.15_2.0.0_ga) to our linux kernel (3.14.28) (ofcourse with resolving conflicts and some changes according to our board)

I'm looking at the psci code, and wondering if `cpu_on` property need not be added to the `dts` file something like this. (Because in `psci.c`,  `of_property_read_u32(np, "cpu_on", &id)` fails)

```
psci {
 		compatible	= "arm,psci-0.2";
 		method		= "smc";
 		cpu_on		= <n>;
 	};
```

**Comment by jeffy1009** [comment] 2017-02-15 08:56
@MrVan Thank you, I succeeded in booting multi-core with 3.14.28 kernel.

The issue was that our kernel didn't have support for psci-0.2. I copied relevant code from linux-4.1 and it works fine now. Thank you very much for your help!

**Comment by jbech-linaro** [comment] 2017-02-15 17:54
@jeffy1009 @MrVan , all, thanks for helping out to get this issue resolved. Because of that I'm closing the issue.

**Comment by jbech-optee-adm** [comment] 2017-02-15 17:54
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Closed by jbech-optee-adm** 2017-02-15 17:54 UTC

**Comment by j824737450** [comment] 2018-01-22 13:02
Sorry, I'm new to optee. Now I have a problem to boot OPTEE. 
![1](https://user-images.githubusercontent.com/33032927/35222015-5796a9a4-ffb7-11e7-90a6-fafb8600d33e.jpg)
It stops at 'starting kernel....'.  What' wrong with it?  Or something else ? 
Thank you!
