### ISSUE TITLE
Compile error with string type CFG_XXX  in plat/conf.mk

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1149] opened 2016-10-29 07:00 UTC
Hi:
When i define a string using CFG_XX  in the platform conf.mk,  i found that if the string contains blanks in the middle such as CFG_STR ?= "aaa  bbb", it will fail to compile? 
Is this problem a bug or a usage restriction?  
Thank you.

**Comment by jforissier** [comment] 2016-10-29 17:09
Hi @prime-zeng,
I would say it's a bug and it should be fixed. If it turns out that it's too difficult to fix, I'll say it's a limitation ;)
Can you give more details on the issue? Such how to reproduce it? Then I will look into it. The bug may be in the way you are using the string (insufficient quoting).

**Comment by prime-zeng** [comment] 2016-10-30 03:24
@jforissier got it, you can reproduce it by adding CFG_STRING ?= "test string"  in your platform conf.mk.( there must exsit blank in the string).

**Comment by jforissier** [comment] 2016-10-31 08:53
Hopefully fixed in https://github.com/OP-TEE/optee_os/pull/1150. Let me know if that works for you.

**Comment by jbech-optee-adm** [comment] 2016-11-03 12:26
Closing the PR since it has been merged manually and verified by reporter.

**Closed by jbech-optee-adm** 2016-11-03 12:26 UTC
