### ISSUE TITLE
OPTEE_SMC_OWNER_TRUSTED_OS is not checked?

### ISSUE THREAD

**Issue by dryvenn** [OP-TEE/optee_os#1401] opened 2017-03-09 10:26 UTC
Hi folks,

I don't know whether this is a bug, but I got stuck for several days, so maybe it's worth changing something!

When I tried to `modprobe optee` from Linux, the command would hang during the call to `optee_enable_shm_cache` ([there](https://github.com/linaro-swg/linux/blob/optee/drivers/tee/optee/call.c#L398)). It appeared that this was because all my threads were suspended instead of being active, and I think I figured out why:

1. OP-TEE jumps into non-secure world, at this point, thread0 is active (then freed) and thread1 is free.

2. A stage0 bootloader loads and jumps to U-Boot.

3. U-Boot does a rogue SMC, with r0=0x1.

4. Because OP-TEE doesn't check the OPTEE_SMC_OWNER_*, the execution goes through a series of "else":
a. `std_smc_entry` instead of `fast_smc_entry` in "sm/smc.c"
b. `thread_alloc_and_run` instead of `thread_resume_from_rpc` in "thread_handle_std_smc"

5. Then `thread_resume` is called, and for a reason that I don't quite understand, `thread_state_suspend` is then called too (but not `tee_entry_std`).

Can you share some insight on what is expected behavior and what isn't? Do you want me to run more tests? Don't you think the owner/validity of the SMC should be checked in "sm/sm.c"?

Thanks!

**Comment by jenswi-linaro** [comment] 2017-03-13 10:13
The problem seems to be that `thread_state_suspend()` is called before the smc ID is checked in `tee_entry_std()`.

Validating SMC id earlier would just hide the problem with `thread_state_suspend()` being called too early and also make it harder for platforms to add extensions.

It looks like the problem is `__thread_std_smc_entry()` doing an RPC even if SMC ID isn't `OPTEE_SMC_CALL_WITH_ARG`. It would better to do the RPC calls (direct or indirect) from `tee_entry_std()` after the call to `thread_set_foreign_intr()`.

**Comment by etienne-lms** [comment] 2017-03-13 10:20
A comment aside from the analysis provided by @jenswi-linaro.

> U-Boot does a rogue SMC, with r0=0x1.

Why should u-boot issue a rogue SMC ? It is not recommended. It could get your OP-TEE into a state you system does not expect (imagine some day the SMC ID "0x1" is bound an architecture "reset target" service for the platform you use).

**Comment by dryvenn** [comment] 2017-03-13 11:02
Hi guys,
Thanks for the replies.

> Validating SMC id earlier would just hide the problem with thread_state_suspend() being called too early and also make it harder for platforms to add extensions.

I suppose that by "too early" you mean "too early in the boot sequence"? I don't know whether this is a problem or not, maybe platforms should be free to do SMC/RPC even in their Linux bootloaders.

Preserving the ability to extend is indeed very important, so what about having a weak function doing the switch on the SMC ID in "sm/sm.c"? That would allow platforms to have custom behavior on the ID of their choice, and it's kind of what CFG_PSCI_ARM32 already does.

> the RPC calls (direct or indirect)

What is the difference between direct and indirect RPC calls?

> Why should u-boot issue a rogue SMC ?

Our current trusted OS implements this SMC to enable/disable the L2 cache, and U-Boot uses that to prepare the ground for Linux. I mixed up my U-Boot versions at some point, causing this SMC to be issued with OP-TEE running. I removed the SMC since, but I thought this was worth opening an issue.

**Comment by jenswi-linaro** [comment] 2017-03-14 13:38
> I suppose that by "too early" you mean "too early in the boot sequence"? I don't know whether this is a problem or not, maybe platforms should be free to do SMC/RPC even in their Linux bootloaders.

Sorry for being unclear, I meant doing RPC before we've verified that it's a `OPTEE_SMC_CALL_WITH_ARG` or some vendor extension that also can handle RPC.

> Preserving the ability to extend is indeed very important, so what about having a weak function doing the switch on the SMC ID in "sm/sm.c"? That would allow platforms to have custom behavior on the ID of their choice, and it's kind of what CFG_PSCI_ARM32 already does.

A weak function there would introduce overhead in the critical path also for platforms that doesn't need any extensions. It's also not a very practical place to take a different route for a platform doing extensions. We'll need to reorganize ` __thread_std_smc_entry()` and `tee_entry_std()` a bit to deal with this in a flexible way.

> What is the difference between direct and indirect RPC calls?

Doing it by calling for instance `thread_rpc_alloc_arg()` directly, or by calling some function that further down the chain calls a function doing an RPC.

**Closed** 2017-04-24 14:33 UTC
