### ISSUE TITLE
Porting OP-TEE OS on i.MX6 DL sabre SD

### ISSUE THREAD

**Issue by ThomasL01** [OP-TEE/optee_os#1245] opened 2016-12-21 08:57 UTC
Hello everybody,

I am currently working on the i.MX6DL SABRE Smart Device trying to port the OP-TEE OS for gateway platform solutions.
I have looked at many requests and issues already available on the github project without finding any solution yet. I hope one of you could help me on this issue.

I followed the Github instructions (4.6 for the Freescale MX6UL EVK) step by step in order to get it works on my board. So I did:

1. Compile and flash U-Boot for the imx6dlsabresd board and I have added options (an appropriate defconfig file has been written like for the 14x14 evk board) such as:

- TEE_RAM_SIZE = 0x40000000
- ARMV7_TEE
- ARMV7_NONSEC
- OPTEE_ENTRY = 0x4E000000

2. Get the kernet, patch it, compile it and flash it.

3. Get the OP-TEE OS and compile it with PLATFORM_FLAVOR=mx6qsabresd.

4. Also get an appropriate device tree and a rootfs.

The board starts booting and U-Boot starts. As you can see on the next screenshot, files are loaded at these addresses:

- zImage: 0x12000000
- device_tree: 0x18000000
- optee.bin: 0x40000000 (OPTEE-ENTRY)

![unnamed](https://cloud.githubusercontent.com/assets/24694095/21382964/b45866a6-c763-11e6-9e2a-1a0c0105677f.png)

And so the kernel starts booting and optee_os goes to an issue while execution. With a gdb debugger I tried to find the source and it happened to have a memory overlap (in step by step execution the code breaks du to overlap). 

I got the follwing error (see the DEBUG trace on the screenshot) that "Physical mem map overlaps 0xa00000" which coresponds to the GIC_BASE memory. It seems the PL310 is overlaping the GIC memory. But in the "platform_config.h" addresses are given such as described in the datasheet:

- 0xA00000: GIC_BASE
- 0xA02000: PL310_BASE

Also defined a 2 cores processor for i.mx6 dual lite
So my questions are do you have any idea why I got this issue and if there is a simple way to correct it?
And also I tried to implement the code for the i.mx6dlsabresd board which is certainly different than the evk board, so is there a simple way to make it works for my board or is it too complicated to adapt the configurations?

Thanks for your support,
Thomas

**Comment by etienne-lms** [comment] 2017-01-04 10:35
hello Thomas, 

The trace "`Physical mem map overlaps 0xa00000`" does not highlight a real issue. As both GIC and PL310 iomem are mapped with the same attributes, optee core nicely handle this overlapping during its inits. Note that it's only a `DEBUG` trace. A real memory overlapping issue would rather cause an `ERROR:` trace and a panic.

> And so the kernel starts booting and optee_os goes to an issue while execution

Could you detail your experience? From the trace you provide, it seems linux kernel it not even booted, but maybe you only provide the early boot traces. Did you run some optee `xtest` (from optee_test) and get some error, hang or any unexpected behaviour ?
From your trace, I rather feel optee core inits are not completed and are wait for some secondary boot cores.

**Comment by ThomasL01** [comment] 2017-01-05 10:01
Hello etienne-lms,

Sorry about the lack of information on the screenshot. What happened after this is a reboot and the board run U-boot again. 

What i did is disasembly optee-os with objdump in order to follow its execution with gdb. While step-by-step execution with gdb, there is a moment where the os is executing unknow code as if the memory went overlap or erased and written by something else. And so a "unknow instructions" is reached and the OS is stops, the board reboot. I can't run any xtest at this point I guess.

>  From the trace you provide, it seems linux kernel it not even booted

Does the kernel has to boot before the optee-os? Is there any boot order between the kernel, optee-os and others OS?

Thanks for your answer,
Thomas

**Comment by etienne-lms** [comment] 2017-01-05 10:27
> Does the kernel has to boot before the optee-os?
> Is there any boot order between the kernel, optee-os and others OS?

In current implementation, it is mandatory that optee core is initialized before the boot stages reach the NonSecure state. As linux kernel is booted in non-secure state, then optee core must boot/init before linux kernel.
If you linux kernel boots fine, then optee inits completed for all cpu cores. You need a running linux kernel to test the optee, with `xtest` for example.

> (...) there is a moment where the os is executing unknow code (...)

If you end up in some corrupted memory content while optee initializes, maybe crosscheck the cache management. I think the optee cache handling is fine. Did the u-boot flushed the cache before branching to optee ? ARMv7 optee inits do disable and invalidate caches. Hence if u-boot left some data in the cache, loaded optee os image might be corrupted in memory.

**Comment by jbech-optee-adm** [comment] 2017-02-15 17:50
We're closing this issue since we think the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Closed by jbech-optee-adm** 2017-02-15 17:50 UTC
